Нартов Никита
urfu-2016/markup-task-4 pull request #10
Opened 2016-10-29 09:53 UTC by nikitc

2016-10-29 09:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-29 09:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-30 17:32 UTC, Lakate commented on index.html
> +            <img class="img-left" src="images/gagarin.jpg" alt="Gagarin">
`alt` нужен для того, чтобы люди с ограниченными возможностями могли использовав специальные расширения понять, что нарисовано. Так что тут лучше стараться давать развернутый ответ, чтобы было понятно и без картинки, что на ней

2016-10-30 17:32 UTC, Lakate commented on index.html
> +            <p>12 апреля 1961 г. в Советском Союзе выведен на орбиту вокруг
`datetime` для даты

2016-10-30 17:32 UTC, Lakate commented on index.html
>  <body>
вам рассказывали про семантическую разметку - давай будем использовать возможности `html5` по максимуму. Посмотри еще раз первую презентацию https://rawgit.com/urfu-2016/markup-slides/master/01-html/index.html#/43

2016-10-30 17:32 UTC, Lakate commented on index.html
> +                <p class="date">12 апреля 1961 года.</p>
`datetime`

2016-10-30 17:32 UTC, Lakate commented on index.html
> +            <div class="day">12 апреля 1961 года- Товарищ, запомни этот день!</div>
`datetime`

2016-10-30 17:32 UTC, Lakate commented on index.css
> +    src: url(fonts/ImpactRegular.woff);
Вам Олег наверняка рассказывал, что одного типа шрифта для кроссбраузерности недостаточно. И когда шрифтов довольно много, хорошая практика выносить их в отдельный файл

2016-10-30 17:32 UTC, Lakate commented on index.css
> +p::first-letter
не стоит писать стили к тегам. Это сейчас у тебя один небольшой файл. А когда верстки много и она сложная ты просто забудешь ниже, что у тебя для всех параграфов первая буква особенная, и как-нибудь переопредилишь. И потом нужно долго искать в чем ошибка. 
Лучше пиши стили к классам

2016-10-30 17:32 UTC, Lakate commented on index.css
> +p
аналогично, лучше заведи класс

2016-10-30 17:35 UTC, Lakate commented
Никита, привет!
Посмотрела твое решение. Вижу 3 минуса, которые обязательно надо поправить
1) семантическая разметка
2) кроссбраузерные шрифты
3) кроссбраузерная верстка. Воспользуйся сайтом http://caniuse.com , чтобы посмотреть какие префиксы необходимо добавить. Для сравнения смотрю в Яндекс.Браузере: 
![1](https://cloud.githubusercontent.com/assets/8994274/19838440/749d84b6-9ef9-11e6-8fab-d85a7a449964.png)

и в FireFox:
![2](https://cloud.githubusercontent.com/assets/8994274/19838443/7e39726e-9ef9-11e6-8633-fb8cfe525413.png)

2016-10-30 17:37 UTC, Lakate commented on index.css
> +    font-size: 13px;
почему 13??? он же становится меньше тогда(((((((

2016-10-30 17:37 UTC, Lakate commented
🍅

2016-10-31 18:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 18:22 UTC, Lakate commented on index.css
> +::first-letter
не надо так делать. Вообще не надо обощать на всё. 
Лучше выдели класс и к нему применяй стили

2016-11-01 18:22 UTC, Lakate commented on index.css
> +td
лучше тоже создать классы

2016-11-01 18:22 UTC, Lakate commented on index.html
> +            <td>Четверг 13 апреля 1961 г.</td>
`datetime`

2016-11-01 18:23 UTC, Lakate commented
упс
![screenshot at 01 23-21-50](https://cloud.githubusercontent.com/assets/8994274/19901781/218bc1b0-a08a-11e6-82d4-88db3fe64ac7.png)

2016-11-01 18:24 UTC, Lakate commented
после увеличения шрифта, картинка съезжает вниз((((
![screenshot at 01 23-24-25](https://cloud.githubusercontent.com/assets/8994274/19901845/568e93a6-a08a-11e6-8c0d-ad8a3abed7ca.png)

2016-11-01 18:30 UTC, Lakate commented on index.css
> +        format('woff'), url(fonts/ImpactRegular.ttf) format('ttf');
лучше `woff` + `woff2` или `woff` + `eot`

2016-11-01 18:30 UTC, Lakate commented on index.css
> +    float: left;
попробуй без плавающих элементов обойтись в этом задании

2016-11-01 18:30 UTC, Lakate commented on index.css
> +    outline: 2px solid black;
цвета надо указывать с помощью hex или rgb

2016-11-01 18:30 UTC, Lakate commented on index.css
> +    font-family: ImpactRegular;
лучше указывать все параметры, чтобы если что подключился нужный дефолтный шрифт

2016-11-01 18:30 UTC, Lakate commented on index.css
> +    column-rule: 1px solid black;
Безвендорное правило всегда идет после правил с вендорными префиксами, даже если оно никем не поддерживается

2016-11-01 18:30 UTC, Lakate commented
не увидела особо семантической разметки(

2016-11-01 18:31 UTC, Lakate commented
🍅

2016-11-02 11:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 11:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 09:21 UTC, Lakate commented on index.html
> +    <input type="checkbox" class="black-white-mode">Черно-белый режим<br>
давай соблюдать отсупы для вложенных тегов

2016-11-04 09:21 UTC, Lakate commented on index.html
> +    <input type="checkbox" class="black-white-mode">Черно-белый режим<br>
еще обычно хочется не просто попадать в этот крестик или кружочек, а еще и по клику на подпись, тоже происходило действие. Советую обратить внимание на тег `label`

2016-11-04 09:21 UTC, Lakate commented on index.html
> +        <article class="time-column">
хм, а до этого что было? не статья? или я чего-то не понимаю? почему там просто параграфы, а тут `article`?

2016-11-04 09:21 UTC, Lakate commented on index.html
> +            <header class="caption-after">Мир рукоплещет юрию гагарину</header>
не стоит так использовать `header`. Он должен быть один. А в нем уже могу быть блоки

2016-11-04 09:21 UTC, Lakate commented on index.html
> +</main>
посмотри еще внимательно по файлу, хочется чтобы была правильная вложенность везде. Так и читабельность кода лучше и смотреться он будет гораздо аккуратней

2016-11-04 09:21 UTC, Lakate commented on index.css
> +        format('woff'), url(fonts/ImpactRegular.eot) format('eot');
странный перенос, конечно, но да ладно)

2016-11-04 09:21 UTC, Lakate commented on index.css
> +h1
уже писала про применение стилей к тегам. Либо добавь, что он относится к классу `topic`, либо добавь класс к самому `h1`

2016-11-04 09:21 UTC, Lakate commented on index.css
> +    font-size: 15px;
почему не просто `font`?

2016-11-04 09:21 UTC, Lakate commented on index.css
> +
лишняя строка

2016-11-04 09:21 UTC, Lakate commented on index.css
> +    font-size: 15px;
вижу, что у тебя везде точное значение размеров шрифта. Давай попробуем использовать еще и `em`. 
Смотри, например, ты захочешь в параграфах изменить дефолтный размер шрифта. Тогда тебе его надо будет поменять везде. А если бы у тебя стояло тут, например, `2em`, то он автоматически увеличивался от измененных размеров шрифта

2016-11-04 09:21 UTC, Lakate commented on index.css
> +    font-family: YesevaOne, Helvetica;
Олег наверняка рассказывал вам про такую оптимизацию как указывание стилей для загружаемых текстов как можно раньше в файле. Потому что, до тех пор пока мы не встретим его, текст загружен не будет. Давай все такие стили унесем наверх

2016-11-04 09:22 UTC, Lakate commented
🍅

2016-11-04 13:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 13:38 UTC, Lakate commented
![screenshot at 04 18-38-17](https://cloud.githubusercontent.com/assets/8994274/20007405/4ae3a79c-a2c6-11e6-9861-cda47589aa37.png)

2016-11-04 13:39 UTC, Lakate commented
🚀

2016-11-05 09:30 UTC, VorontsovMaxim requested changes
🍅 
Еще нужно исправить черно-белый режим

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    text-align: justify;
В данном случае это правило не работает. Оно применяется ко всем строкам текста за исключением последней, соответственно когда строка одна оно просто не применяется

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    text-transform: uppercase;
Можно же в верстке написать заглавными буквами сразу)

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin: 0 auto;
Достаточно просто `margin: 0`, потому что `h1` растянут на всю ширину `header` и по бокам будут отступы 0

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin: 0 auto;
Про `text-transform` и `margin` аналогично `.topic h1`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin-bottom: 0;
Аналогично, можно объединить `margin: 0`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    text-transform: uppercase;
Ну и здесь аналогично

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +        format('woff'), url(fonts/ImpactRegular.eot) format('eot');
Для шрифтов еще необходимо указать `local`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    word-break: normal;
`normal` - значение по умолчанию, его можно не указывать

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    font-weight: bold;
Давай `font-family`, `font-size` и `font-weight` объединим в одно правило `font`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    overflow: hidden;
Для чего используется `vertical-align: top` и `overflow: hidden` ? Кажется, что можно обойтись и без них

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    word-break: normal;
`normal` - значение по умолчанию

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin-bottom: 2px;
Зачем здесь отступ снизу?

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +        <input type="checkbox" class="black-white-mode" id="bwm">
лучше давать более осмысленные имена, а не сокращать

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +        <hr>
Этот `hr` можно сделать как `border-top` у ниже идущего header'а

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +                <hr>
И этот

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +                <p>12 апреля 1961 г. в Советском Союзе выведен на орбиту вокруг
Все тексты лучше предварительно прогонять через сервис, который расставит мягкие переносы
Например [этот](http://quittance.ru/hyphenator.php)

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +                    <p>Свершилось великое событие. Впервые в истории человек осуществил полет в космос.
Мне кажется в исходном тексте разбиение на абзацы было. Поленился разбить?)

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +                    Товарищ, запомни этот день!</time>
В тег `time` лучше помещать только дату, а остальной текст писать вне его

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    width: 100%;
Правда ли нужны `width` и `vertical-align`?

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    white-space: pre-wrap;
Зачем `pre-wrap`?

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    white-space: pre-wrap;
выше стили применяются к `.release, .cell` и там тоже есть `pre-wrap`, можно не дублировать

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    word-break: normal;
`normal` - значение по умолчанию

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    font-size: 1em;
Луче объединить в одно правило `font`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin: 0 0 10;
точно ничего не забыл?)
Можно использовать `margin-bottom`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    height: auto;
`auto` - значение по умолчанию, его можно не писать

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    display: inline-block;
Классы `.logo, .img-left` применяются к `<img>`, поэтому нет смысла указывать `display: inline-block`, потому что `<img>` является `inline-block` элементом по умолчанию

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    font-size: 1em;
Ни одно из этих четырех свойств не дает никакого эффекта. Нужно либо добиться того эффекта, которого хотелось. Либо убрать эти правила

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    font-size: 1em;
`font-size: 1em` можно не указывать

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    margin: 0 auto;
Достаточно `margin: 0`

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.css
> +    display: block;
`<article>` - блочный элемент

2016-11-05 09:30 UTC, VorontsovMaxim commented on index.html
> +        <input type="radio" name="font" id="nf"><label for="nf">Нормальный шрифт</label>
Можно указать, что нормальный шрифт используется по умолчанию

2016-11-05 14:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 16:08 UTC, VorontsovMaxim requested changes
🍅 
Есть еще немного замечаний, в целом уже намного лучше
Обрати внимание на замечания, которые я уже писал, некоторые из них ты так и не исправил
Еще пробегись по всему html файлу и правильно расставь отступы и переносы строк, так твой код будет выглядеть лучше

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.css
> +    font-weight: bolder;
`font-family`, `font-size` и `font-weight` нужно объединить одним правилом `font`

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.css
> +    white-space: pre-wrap;
Вопрос по-прежнему остался

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.css
> +    font: italic 1em;
при использовании правила `font` обязательно необходимо указывать семейство шрифтов

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.css
> +    font-size: 2em;
Можно объединить эти два правила

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.html
> +                <p class="sign">Юрий Алексеевич Гагарин</p>
Картинку и подпись к ней лучше оформить используя тег `<figure>`

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.html
> +                    <p><time datetime="1961-04-12">12 апреля 1961 года</time>
Еще давай сразу всегда хорошо расставлять отступы и переносы строк. Например в этой ситуации на мой взгляд выглядело бы читабельнее с таким форматированием:
```html
<p>
    <time>дата</time> текст
</p>
```

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.html
> +                    Советскому космонавту, впервые в мире совершившему космический полет
Здесь должен быть отступ в на 4 пробела больше

2016-11-05 16:08 UTC, VorontsovMaxim commented on index.css
> +    word-break: normal;
Я уже писал, что `normal` - это значение по умолчанию

2016-11-05 16:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 05:53 UTC, VorontsovMaxim approved these changes

2016-11-07 05:53 UTC, closed without merging