Соловьев Александр
urfu-2016/markup-task-4 pull request #17
Opened 2016-10-29 23:36 UTC by AlSoEdit

2016-10-29 23:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-29 23:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-30 12:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-31 16:08 UTC, onufrienko commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One" rel="stylesheet">
Не хочешь попробовать подключить шрифты не с google fonts?

2016-10-31 16:11 UTC, onufrienko commented
Здесь было бы неплохо добавить отступов
![image](https://cloud.githubusercontent.com/assets/14929766/19861502/95738bd0-9fae-11e6-8153-5ca53ccbb4be.png)

2016-10-31 16:12 UTC, onufrienko commented
И еще не вижу, чтобы писалось что-нибудь
В
О
Т

Т
А
К

2016-10-31 16:13 UTC, onufrienko commented on index.html
> +        <img src="https://www.svgimages.com/svg-image/s5/james-bond-stencil-256x256.png" alt="James Bond">
У картинок нужен атрибут title

2016-10-31 16:15 UTC, onufrienko commented on index.html
> +        <div class="columns_paragraps">
В качестве разделителя лучше использовать "-"

2016-10-31 16:16 UTC, onufrienko commented on index.html
> +        <h1>The essential 'isms' of Bond</h1>
Можно использовать тег header

2016-10-31 16:17 UTC, onufrienko commented
Картинка есть, но она, к сожалению, одна и без подписи :(

2016-10-31 16:21 UTC, onufrienko commented
Немножко странно едет список при уменьшении экрана
![image](https://cloud.githubusercontent.com/assets/14929766/19861844/e6fa69aa-9faf-11e6-9d99-7ac82feedd43.png)

2016-10-31 16:22 UTC, onufrienko commented on index.css
> +    float: right;
Плавающие элементы в этом задании не должны быть использованы

2016-10-31 16:26 UTC, onufrienko commented
:tomato:

2016-10-31 16:28 UTC, onufrienko commented
Кстати, если будешь подключать шрифты, то неплохо будет использовать и атрибут local

2016-11-02 14:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-02 14:54 UTC, AlSoEdit commented
🍏

2016-11-02 15:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 07:29 UTC, onufrienko commented on index.html
> +                    alt="James Bond" title="Vector representation of the stencil of James Bond">
title? :)

2016-11-04 07:30 UTC, onufrienko commented
Пое-е-ехало :(
![image](https://cloud.githubusercontent.com/assets/14929766/19997726/96536b6a-a279-11e6-9783-1d4f12815565.png)
![image](https://cloud.githubusercontent.com/assets/14929766/19997746/ac9bfbc6-a279-11e6-8f94-b1836662d249.png)

2016-11-04 07:31 UTC, onufrienko commented
Молодец, что всё-таки сделал :)
![image](https://cloud.githubusercontent.com/assets/14929766/19997759/bef7af68-a279-11e6-8cbf-258d24b7037e.png)

2016-11-04 07:31 UTC, onufrienko commented
🍅

2016-11-04 12:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 12:39 UTC, AlSoEdit commented
🍏

2016-11-04 19:39 UTC, onufrienko commented
:tomato:

2016-11-05 04:47 UTC, mokhov requested changes
🍅

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    src: local('Josefin Slab Bold'), url('fonts/JosefinSlab-Bold.eot')
Почему тут local('Josefin Slab Bold') там и правда такое имя зашито?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    text-align: center;
Этот стиль лучше унести вниз к другим (на самом деле одному) стилю h2.

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    width: 1%;
А расскажи что тут происходит и почему так?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    font-family: Helvetica, sans-serif;
Почему нельзя шрифт задавать чисто у article и переопределить его там, где шрифт отличается?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    font-size: .6em;
Здесь точно какой-то оверхед, размеры должны меняться в одном месте и наследоваться всеми (иначе зачем вообще нужен em)

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    -moz-column-count: 4;
Не понятно, почему для всех браузеров ты задал ширину колонки, а для Firefox количество?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    -moz-column-count: 4;
Ну и есть такое правило: сначала пишутся правила с вендорными префиксами, а потом без

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    font: 15px 'Crete Round', serif;
Почему здесь в px размеры?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    margin-top: -5%;
Вертикальные `margin` очень редко бывают в процентах (и про это рассказывали на последней лекции почему). Ну и да, вероятно ты не знаешь как победить вот эту особенность http://stackoverflow.com/questions/10844205/html-5-strange-img-always-adds-3px-margin-at-bottom

2016-11-05 04:47 UTC, mokhov commented on index.css
> +    font-size: 1.5em;
Эти стили 1 в 1 такие же как в правиле выше

2016-11-05 04:47 UTC, mokhov commented on index.css
> +.quote
Для цитат есть специальный тег

2016-11-05 04:47 UTC, mokhov commented on index.css
> +.paragraph
Почему нельзя было задать тегу?

2016-11-05 04:47 UTC, mokhov commented on index.css
> +.first-paragraph
Для выбора первого элемента есть специальный селектор

2016-11-05 04:47 UTC, mokhov commented on index.html
> +    <label for="theme">Black theme</label>
А сможешь придумать способ сделать так, чтобы все эти input/label'ы были вне газеты, т.е на отдельной плашке, например

2016-11-05 04:47 UTC, mokhov commented on index.html
> +            <aside>Bond</aside>
Кажется здесь ты некорректно используешь тег aside http://htmlbook.ru/html/aside

2016-11-05 04:47 UTC, mokhov commented on index.html
> +            <h2>ENVIED</h2>
Есть CSS свойство которое позволяет приводить текст к верхнему регистру

2016-11-05 04:47 UTC, mokhov commented on index.html
> +            GUARDIAN, Mentreal, January 29, 1966 &#8212; 3
Здесь есть дата, но нет тега даты :(

2016-11-05 08:02 UTC, AlSoEdit commented on index.css
> +    src: local('Josefin Slab Bold'), url('fonts/JosefinSlab-Bold.eot')
Правда
![image](https://cloud.githubusercontent.com/assets/14929897/20028598/fd263eba-a357-11e6-9d79-6bbe05a67cf5.png)

2016-11-05 08:11 UTC, AlSoEdit commented on index.css
> +    width: 1%;
break-word добавляет перенос строк там, где слово не вмещается в блок по ширине
Я задаю заведомо маленькую ширину, чтобы перенос происходил как можно чаще (т.е. после каждой буквы)
На самом деле 1% это слишком мало и для буквы по ширине, но дальше уменьшать уже некуда, поэтому блоку приходиться оставить минимальную единицу текста (символ)

2016-11-05 08:19 UTC, AlSoEdit commented on index.css
> +    font-family: Helvetica, sans-serif;
У меня ведь изначально заданы шрифты для каждого отдельного элемента из перечисленных, поэтому чтобы их поменять мне надо явно к ним обратиться, т.к. селектор .helvetica-font:checked ~ article будет переопределен для каждого элемента более специфичными селекторами, поэтому я не могу так написать
Ну или я чего-то не понимаю

2016-11-05 08:26 UTC, AlSoEdit commented on index.css
> +    -moz-column-count: 4;
Если честно, я не думал, что это взаимоисключающие вещи. =\
А еще я думал, что свойство с префиксом = обычное свойство + указание конкретному браузеру, но похоже, что нет

2016-11-05 08:28 UTC, AlSoEdit commented on index.css
> +    font: 15px 'Crete Round', serif;
Не помню
Осталось, наверное, от самого начального варианта, не заметил

2016-11-05 08:31 UTC, AlSoEdit commented on index.css
> +    margin-top: -5%;
Этот margin мне и не нужен уже, вроде
Остался от каких-то предыдущих версий, когда был полезен
Убрал

2016-11-05 08:40 UTC, AlSoEdit commented on index.css
> +.first-paragraph
Не совсем то имеется в виду
Он первый да, но лежит вне блока колонок, в котором лежат все остальные параграфы, поэтому вроде нет особого смысла обращаться к первому, потому что он единственный дочерний в article, поэтому написал article > p

2016-11-05 08:43 UTC, AlSoEdit commented on index.css
> +.paragraph
В данном варианте точно можно
Возможно, в предыдущих версиях разметка была другая, и это как-то использовалось (но это не точно)
Хотя с другой стороны где-то я видел, что хорошей практикой является всё оборачивать в классы, т.к. в больших проектах очень много всего, так что можно промахнуться в селекторах по тегам (но при этом у меня не всё так обернуто, противоречие, да)
Поправьте, если ошибаюсь

2016-11-05 08:48 UTC, AlSoEdit commented on index.html
> +            <h2>ENVIED</h2>
Да, есть, я его даже использовал в aside :)
Для любого текста в верхнем регистре надо так делать? (например в footer - часть верхним, часть нет)
Или только для тех случаев, когда всё содержимое элемента написано верхним регистром?

2016-11-05 18:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 18:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 18:38 UTC, AlSoEdit commented
🍏

2016-11-05 19:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 19:25 UTC, AlSoEdit commented on index.css
> +.first-paragraph
Хотя всё таки будет лучше с селектором :first-type-of(p), вдруг после колонок допишу еще параграф, чтобы наверняка

2016-11-05 19:25 UTC, AlSoEdit commented
🍏

2016-11-07 19:31 UTC, mokhov commented
Как-то грустно стало :(
![screen shot 2016-11-07 at 16 18 25](https://cloud.githubusercontent.com/assets/357689/20072551/e778ed0e-a539-11e6-8ba0-8c2685411316.jpeg)

2016-11-07 19:32 UTC, mokhov commented
Как-то грустно стало :(
![the essential isms of bond 2016-11-07 22-32-21](https://cloud.githubusercontent.com/assets/357689/20072612/1cafad28-a53a-11e6-8a8f-e56f9979c4a3.png)

2016-11-07 19:33 UTC, mokhov commented on index.css
> +    font-family: Helvetica, sans-serif;
Ну так и вопрос – зачем ты задаешь каждому явно, а не контейнеру?

2016-11-07 19:34 UTC, closed without merging