Кулешова Ирина
urfu-2016/markup-task-4 pull request #19
Opened 2016-10-30 09:59 UTC by trtz

2016-10-30 10:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 10:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-31 11:56 UTC, mironov-alexey commented on index.css
> +    src: url(fonts/dreamscar.ttf);
Добавь ещё шрифты в формате `woff` или `woff2`. Будет круто, если ещё формат `eot` добавишь

2016-11-01 08:16 UTC, mironov-alexey commented on index.css
> +.smallcolumns
`wide-columns` через `-`, а тут -- нет

2016-11-01 08:17 UTC, mironov-alexey commented on index.css
> +.smallcolumns
ну и класс можно в единственном числе называть

2016-11-01 08:18 UTC, mironov-alexey commented on index.css
> +.right
не понятно, что за `right`. Лучше назвать чуть более подробно

2016-11-01 08:40 UTC, m1ralx requested changes

2016-11-01 08:40 UTC, mironov-alexey commented on index.css
> +    font-family: Georgia, serif;
основной шрифт лучше указывать у родительского элемента -- body

2016-11-01 08:40 UTC, mironov-alexey commented on index.css
> +    src: url(fonts/dreamscar.ttf);
и атрибут `local` нужен

2016-11-01 08:40 UTC, mironov-alexey commented on index.html
> +<div class="vertical">Особый вид куниц неоднороден по составу</div>
чёт пробелы не видно
![image](https://cloud.githubusercontent.com/assets/6783167/19883827/2bd12ee6-a038-11e6-9858-2ac38a33b500.png)

2016-11-01 08:40 UTC, mironov-alexey commented on index.html
> +<div class="table-like-section"><h3>Цитата недели</h3>
если это правда секция,  то есть специальный тег --  `section`

2016-11-01 08:40 UTC, mironov-alexey commented on index.html
> +<h3>Квантовый гамма-квант: методология и особенности</h3>
вложенные элементы лучше выделять отступами

2016-11-01 08:42 UTC, mironov-alexey commented
🍅

2016-11-05 14:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 14:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 14:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 15:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 15:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 15:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 15:08 UTC, trtz commented
🍏

2016-11-06 06:58 UTC, mironov-alexey commented
🚀

2016-11-08 08:53 UTC, mokhov requested changes
🍅

2016-11-08 08:53 UTC, mokhov commented on index.html
> +        <p>Анжамбеман приводит пульсар. Очевидно, что широта синхронизует декаданс.
Отступы поехали :(

2016-11-08 08:53 UTC, mokhov commented on index.html
> +    <q>Попугай интуитивно понятен. Бамбук, как бы это ни казалось парадоксальным, входит коралловый риф,
Очень хочется прогнать это через типограф

2016-11-08 08:53 UTC, mokhov commented on index.html
> +    <q>Попугай интуитивно понятен. Бамбук, как бы это ни казалось парадоксальным, входит коралловый риф,
А ещё кажется что `blockquote` здесь более семантичен

2016-11-08 08:53 UTC, mokhov commented on index.css
> +    column-count: 2;
Обычно вендорные префиксы пишутся до правила без вендоров

2016-11-08 13:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 13:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 16:26 UTC, trtz commented
🍏

2016-11-10 16:19 UTC, mokhov requested changes
🍅

2016-11-10 16:19 UTC, mokhov commented on index.css
> +    position: absolute;
Хочется чтобы колонки были реализованы иначе, нежели абсолютным позиционированием

2016-11-10 16:19 UTC, mokhov commented on index.css
> +    column-width: 100px;
Сначала вендорные префиксы, потом без вендорные

2016-11-10 16:19 UTC, mokhov commented on index.css
> +    font-size: 120px;
Можно объединить с предыдущим свойством

2016-11-10 16:19 UTC, mokhov commented on index.css
> +    -webkit-column-count: 2;
А тут правильная лесенка, как же так?

2016-11-10 16:19 UTC, mokhov commented on index.html
> +<div class="vertical"><p>Особый</p><p>вид</p><p>куниц</p><p>неоднороден</p><p>по</p><p>составу</p></div>
А зачем разные теги p, если просто вставлять пробелы, то не получится?

2016-11-10 18:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-10 18:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-10 18:38 UTC, trtz commented on index.html
> +<div class="vertical"><p>Особый</p><p>вид</p><p>куниц</p><p>неоднороден</p><p>по</p><p>составу</p></div>
Не могу придумать ничего лучше: пробелы игнорируются, `<br>` тоже, `&nbsp;` спасает не везде

2016-11-12 21:09 UTC, mokhov commented on index.html
> +<div class="vertical"><p>Особый</p><p>вид</p><p>куниц</p><p>неоднороден</p><p>по</p><p>составу</p></div>
> &nbsp; спасает не везде
что значит не везде?

2016-11-12 21:10 UTC, closed without merging