Шмакова Мария
urfu-2016/markup-task-4 pull request #20
Opened 2016-10-30 11:04 UTC by MariaShmakova

2016-10-30 11:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 08:48 UTC, mironov-alexey commented
ааа, что происходит
![image](https://cloud.githubusercontent.com/assets/6783167/19884078/bc7eb494-a039-11e6-9f76-8fe0ad1d67d7.png)
![image](https://cloud.githubusercontent.com/assets/6783167/19884090/d0e9f952-a039-11e6-9090-737220cc269f.png)

2016-11-01 09:03 UTC, mironov-alexey commented
не нашел реализации последнего пункта требований

2016-11-01 09:04 UTC, m1ralx commented on index.css
> +    font-style: normal;
нужен атрибут `local`

2016-11-01 09:04 UTC, mironov-alexey commented on index.css
> +    src: url('cormorantsc-bold-webfont.woff2') format('woff2'), url('cormorantsc-bold-webfont.woff') format('woff');
какая-тоо длинная строчка. странно, что линтер не орёт

2016-11-01 09:07 UTC, mironov-alexey commented on index.css
> +.leftHead
leftHeader тогда уж

2016-11-01 09:08 UTC, mironov-alexey commented on index.css
> +    font-family: 'cormorant_scbold', bold !important;
что-то неочевидно, зачем тут important. Лучше как-нибудь без него обойтись

2016-11-01 09:12 UTC, mironov-alexey commented
🍅

2016-11-01 19:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-01 19:41 UTC, MariaShmakova commented
:green_apple:

2016-11-01 19:42 UTC, MariaShmakova commented
Ой, извини за ошибочное яблоко, я случайно

2016-11-01 20:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 20:17 UTC, MariaShmakova commented
:green_apple:

2016-11-02 20:31 UTC, mironov-alexey commented
Я всё равно не понимаю, что происходит при наведении на страницу и зачем это?

2016-11-03 09:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-03 10:00 UTC, MariaShmakova commented
:green_apple:

2016-11-06 00:52 UTC, MariaShmakova commented
:green_apple:

2016-11-06 06:32 UTC, mironov-alexey commented
В extra надо на каждую функциональность делать отдельную радиокнопку. Вдруг бабуля захочет обычного размера шрифт на чёрно-белом фоне.  Кстати, я не заметил, чтобы тип шрифта менялся

2016-11-06 06:34 UTC, mironov-alexey commented
🚀

2016-11-07 06:15 UTC, steppefox requested changes
🍅

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    background: url(phone.jpg) 100% 100% no-repeat rgba(232, 200, 120, .8);
Все же `phone` - это в первую очередь телефон. Если эта картинка является фоном, то пожалуйста переименуй соответственно. Пользоваться переводчиком - это нормально))

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    background: url(phoneStars.png) 100% 100% no-repeat black;
Здесь соответственно тоже нужно переименовать

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    columns: 4;
Свойство `columns` - используется для комбинации сразу двух свойств. Если необходимо указывать только количество колонок, то использовать желательно `column-count`

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    margin-top: -25px;
Это явно хак что-бы отровнять картинку. На самом деле нужно обнулять соответствующие margin'ы у `p.img` (родителя картинки) и у заголовка `h2` («Роскосмос» отправит обезьян на Марс).

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    width: 810px;
Данные параметры нужно вынести в аттрибуты width/height в html тэг картинки . Так же, картинка вставлена 1957px шириной, а визуально она 810px. Соответственно, почему бы сразу не использовать нужный размер картинки? Впихивание больших картинок в маленькие контейнеры - плохая практика, это замедляет загрузку страниц и заставляет браузер делать дополнительный repaint при рендеринге.

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    float: right;
В этом задании нельзя использовать `float` элементы. Пожалуйста придумай как обойтись без них =(

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    float: left;
Аналогично

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    float: left;
Аналогично

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    columns: 2;
Аналогично, columns-count

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    float: left;
Аналогично, float - в рамках данного задания нежелательны

2016-11-07 06:15 UTC, steppefox commented on index.css
> +    float: left;
Аналогично

2016-11-07 06:15 UTC, steppefox commented on index.html
> +            <img src="logo.png" alt="Логотип Роскосмоса">
У картинки нужно указать аттрибуты width, height

2016-11-07 06:15 UTC, steppefox commented on index.html
> +                <aside class="verticalText">ВЫПУСК<br><br>7</aside>
Если нужно вывести текст большими буквами, в CSS есть соответствующее свойство

2016-11-07 06:15 UTC, steppefox commented on index.html
> +                    <p class="text">Учё&shy;ные за два го&shy;да под&shy;го&shy;то&shy;вят обе&shy;зьян к
В контенте слишком много `&shy;`

2016-11-07 06:15 UTC, steppefox commented on index.html
> +            <span>Среда, 21 октября, 2015</span>
Здесь есть дата, но нет соответствующего тэга для указания даты =(

2016-11-07 06:15 UTC, steppefox commented on index.html
> +    <input name="choiceNewspaper" type="radio" checked value="Марти" class="firstVersion">&nbsp;Марти
Было бы круто иметь возможность переключаться тыкая на текст, а не целясь в radio. Так же, это только часть `extra` задания, ты успеешь доделать оставшиеся пункты?:
* Возможность увеличить/уменьшить шрифт
* Возможность поменять шрифт на другой, другого типа

В противном случае `extra` засчитать не смогу =(

2016-11-07 06:15 UTC, steppefox commented on index.html
> +                    <p class="img"><img src="cosmosMonkey.jpg" alt="Обезьянка в космосе"></p>
У картинки не хватает аттрибутов width/height

2016-11-07 06:15 UTC, steppefox commented on index.html
> +                    <p><img src="sun.jpg" alt="Солнце">В пла&shy;ны «Ро&shy;с&shy;кос&shy;мо&shy;са»
Исходное изображение больше чем необходимо показывать. Так же не хватает аттрибутов width/height. Не хватает title. Содержимое alt - слишком короткое и не описывает содержимое в точности.

2016-11-07 06:15 UTC, steppefox commented on index.html
> +                        <img src="milkyway.jpg" alt="Солнце">Этот про&shy;цесс не&shy;из&shy;бе&shy;жен,
Исходное изображение больше чем необходимо показывать. Так же не хватает аттрибутов width/height. Не хватает title. Содержимое alt - слишком короткое и не описывает содержимое в точности.

2016-11-07 10:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 10:41 UTC, MariaShmakova commented on index.css
> +    float: left;
Мне линтер запрещает использовать align у картинки:(
Можно мне оставить только в этом случае float?

2016-11-07 10:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 10:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 11:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 11:03 UTC, MariaShmakova commented
:green_apple:

2016-11-07 11:50 UTC, steppefox requested changes
🍅

2016-11-07 11:50 UTC, steppefox commented on index.html
> +            <img src="logo.png" alt="Логотип Роскосмоса" title="Логотип Роскосмоса"
Исходное изображение больше чем изображение на выводе

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    float: left;
В рамках задания не следует использовать плавающие float элементы

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font: 14px bold;
Здесь размер текста тоже должен меняться, попробуй использовать `em`

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font: 42px bold;
Здесь размер текста тоже должен меняться, попробуй использовать `em`

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font: 35px serif;
Жестко заданный размер в `px` =( А должен меняться. К тому же если здесь меняется только размер шрифта, нужно использовать `font-size`

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    overflow: hidden;
Зачем это здесь?

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    height: 100%;
Это здесь не нужно

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font: 14px serif;
Жестко заданный размер в `px` =( А должен меняться. Если изменяется только размер - то нужно использовать `font-size`. К тому же пожалуйста, не используй подобные глобальные правила, дай элементу с датой осмысленный класс и примени правило.

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    hyphens: manual;
Аналогично

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    hyphens: manual;
А это правило в таком виде Chrome точно поддерживает? И оно вообще нужно?

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font: 65px bold;
Заголовок тоже должен менять свой размер. К тому же лучше разбить на два правила, `font-size` и `font-weight`

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    width: 100%;
По умолчанию header блочный элемент, зачем ему width: 100%?

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    src: url('unifrakturmaguntia-book-webfont.woff') format('woff');
Наверное лучше объединить всё в один `src`

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    font-family: Georgia, Arial serif;
Почему первая буква одним шрифтом, а весь остальной текст другим?

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    margin-top: -15px;
Зачем этот хак?

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    display: inline-block;
В Firefox центральная статья уплывает куда-то вниз

2016-11-07 11:50 UTC, steppefox commented on index.css
> +    src: local('Cormorant'), url('cormorantsc-bold-webfont.woff2') format('woff2');
Наверное лучше объединить всё в один `src`

2016-11-07 13:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 13:14 UTC, MariaShmakova commented
:green_apple:

2016-11-07 15:45 UTC, steppefox requested changes
🍅

2016-11-07 15:45 UTC, steppefox commented on index.css
> +    float: left;
Float - нельзя =_=

2016-11-07 15:45 UTC, steppefox commented on index.css
> +    src: local('UnifrakturMaguntia'), url('unifrakturmaguntia-book-webfont.woff2') format('woff2'), url('unifrakturmaguntia-book-webfont.woff') format('woff');
Пожалуйста, сделай переносы после запятых, чтобы красиво выглядело в столбик

2016-11-07 15:45 UTC, steppefox commented on index.css
> +    font-size: 1.1em;
А зачем здесь `em`? oO Так-то это не плохо, но хочется верить что это осознанный шаг, и ты можешь навскидку, без подглядываний в браузер сказать сколько это в px?

2016-11-07 15:45 UTC, steppefox commented on index.css
> +    overflow: hidden;
Вот это точно нужно? oO

2016-11-07 15:48 UTC, MariaShmakova commented on index.css
> +    float: left;
Случайно забыла убрать

2016-11-07 16:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 16:19 UTC, MariaShmakova commented
:green_apple:

2016-11-07 16:30 UTC, steppefox commented
Все здорово, закрываю ^__^

2016-11-07 16:31 UTC, steppefox approved these changes

2016-11-07 16:32 UTC, closed without merging