Сокерин Тимофей
urfu-2016/markup-task-4 pull request #21
Opened 2016-10-30 11:07 UTC by kmn75

markup-task-4 "Верстка газеты".

2016-10-30 11:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 11:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 11:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-30 14:01 UTC, VasiliiKuznecov commented
![2016-10-30 19-00-32](https://cloud.githubusercontent.com/assets/8963033/19837039/33a60c38-9ed3-11e6-87b4-615d82df6965.png)
 Одна картинка растянулась по ширине, другая сузилась

2016-10-30 14:03 UTC, VasiliiKuznecov commented
![2016-10-30 19-02-31](https://cloud.githubusercontent.com/assets/8963033/19837055/7df0d610-9ed3-11e6-9157-ce5dcd8fe5cf.png)
Неплохо было бы сделать какой-нибудь отступ после заголовка, а то прям сливается с газетой

2016-10-30 14:07 UTC, VasiliiKuznecov commented
![2016-10-30 19-06-25](https://cloud.githubusercontent.com/assets/8963033/19837074/00af5798-9ed4-11e6-892e-7ff9fda37c9b.png)
Вот так выглядит в Firefox'е, что-то с колонками не то(

2016-10-30 14:16 UTC, VasiliiKuznecov commented on index.css
> +div.header
Необязательно уточнять, что класс `header` именно у `div`

2016-10-30 14:17 UTC, VasiliiKuznecov commented on index.css
> +div.header
Ну и так везде, где неважно, к какому тегу должен быть привязан класс (обычно так и бывает)

2016-10-30 14:18 UTC, VasiliiKuznecov commented on index.css
> +div.one
Непонятное название селектора

2016-10-30 14:19 UTC, VasiliiKuznecov commented on index.css
> +.ya
не надо сокращать названия классов, и почему не использовать `:first-letter`?

2016-10-30 14:21 UTC, VasiliiKuznecov commented on index.css
> +img
Лучше не использовать в качестве селектора тег, так как теперь у тебя все картинки на странице будут размером 150*200, хотя так не должно быть, они все разного размера

2016-10-30 14:21 UTC, VasiliiKuznecov commented on index.html
> +https://github.com/urfu-2016/markup-task-4">
Почему перенес строчку?)

2016-10-30 14:23 UTC, VasiliiKuznecov commented on index.html
> +<title>Психологическая газета</title>
Следует делать отступы:

``` html
<head>
    <title>...</title>
    ...
</head>
```

2016-10-30 14:23 UTC, VasiliiKuznecov commented on index.html
> +<div class="header">
Должны быть отступы у элементов внутри другого элемента

2016-10-30 14:24 UTC, VasiliiKuznecov commented on index.html
> +<div class="header">
И используй семантичные теги, тут подошел бы тег header

2016-10-30 14:24 UTC, VasiliiKuznecov commented on index.html
> +<div class="one">
Тег `main`

2016-10-30 14:25 UTC, VasiliiKuznecov commented on index.html
> +<p><span class="theme">Тема: «Групповой психоанализ: субъект или сновидение?»</span><br><hr>
тег `article`

2016-10-30 14:30 UTC, VasiliiKuznecov commented on index.html
> +<p><span class="theme">Тема: «Групповой психоанализ: субъект или сновидение?»</span><br><hr>
Вместо `span` можно так же использовать семантичный тег, соответствующий заголовку. И лучше не писать `<br>`, а сделать блочный элемент, тогда следующий элемент будет отображаться с новой строки

2016-10-30 14:30 UTC, VasiliiKuznecov commented on index.html
> +<br>
Вместо разбиения на абзацы с помощью `<br>`, лучше заключать абзацы в тег `<p>`

2016-10-30 14:32 UTC, VasiliiKuznecov commented on index.html
> +позиций психологии. <img src="img/psy.jpg" alt="психоанализ">Наши исследования
у img еще хорошо бы указать атрибут `title`

2016-10-30 14:34 UTC, VasiliiKuznecov commented on index.html
> +<div class="footer">
можно использовать семантический тег `<footer>`

2016-10-30 14:34 UTC, VasiliiKuznecov commented
🍅

2016-11-03 07:09 UTC, kmn75 commented on index.css
> +.ya
:first-letter работает с div, но не работает со span.

2016-11-03 07:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 08:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 09:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 09:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 09:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-03 19:21 UTC, VasiliiKuznecov commented on index.css
> +    column-gap: 20px;
для gap и rule тоже нужны свойства с префиксами, сейчас они не работают в firefox

2016-11-03 19:28 UTC, VasiliiKuznecov commented
Нужно добавить свойства с префиксами для `column-gap` и `column-rule`, а так 🚀

2016-11-04 05:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 04:53 UTC, mokhov requested changes
🍅

2016-11-05 04:53 UTC, mokhov commented on index.css
> +    src: url(decor.TTF);
У меня этот шрифт не подключился. Изучи как правильно подключать шрифты и в каких форматах

2016-11-05 04:53 UTC, mokhov commented on index.css
> +    font-family: Decor, 'Times New Roman';
Хоть и вероятность этого мала, но все-таки нужно указывать последним семейство шрифтов

2016-11-05 04:53 UTC, mokhov commented on index.css
> +    column-count: 4;
Без вендорные правила пишутся после правил с вендорными префиксами

2016-11-05 04:53 UTC, mokhov commented on index.css
> +.img0
Очень плохое и не семантичное именование классов картинок, не отражающее того как будет выглядеть итоговый результат

2016-11-05 04:53 UTC, mokhov commented on index.html
> +            <h4>Тема: «Групповой психоанализ: субъект или сновидение?»</h4><hr>
Сразу h4? Без h1-h3?

2016-11-05 04:53 UTC, mokhov commented on index.html
> +            <p><img class="img1" src="img/psy1.jpg" alt="самонаблюдение" title="самонаблюдение">
Текст внутри alt/title должен отвечать на вопрос: что изображено на картинке?

2016-11-05 04:53 UTC, mokhov commented on index.html
> +            <blockquote><abbr title="Пример использования цитаты">смена</abbr> субмодальностей</blockquote>
Некорректное использование тега `abbr`

2016-11-05 04:53 UTC, mokhov commented on index.html
> +            <a href="https://yandex.ru/referats"><span class="yandex">Я</span>ндекс.Рефераты</a>.
Первую букву можно окрасить в красный цвет без использования доп.элементов

2016-11-05 04:53 UTC, mokhov commented on index.html
> +            <h4>Тема: «Концептуальный код: основные моменты»</h4><hr>
Мы рекомендуем одиночные теги закрывать

2016-11-05 17:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 09:01 UTC, mokhov requested changes
🍅

2016-11-08 09:01 UTC, mokhov commented on index.html
> +            <p>Бессознательное, как это бы ни казалось парадоксальным, дает филогенез. С феноменологической
Тексты хорошо бы через типограф прогнать

2016-11-08 09:01 UTC, mokhov commented on index.html
> +            Психологическая газета (выпуск 1)
header – это секционный тег, а внутри должен быть либо заголовок либо ещё что-то

2016-11-08 09:01 UTC, mokhov commented on index.html
> +            <h1>Тема: «Групповой психоанализ: субъект или сновидение?»</h1><hr>
Можно ли было задать стили h1 и обойтись без hr?

2016-11-08 09:01 UTC, mokhov commented on index.html
> +            <h2><a href="https://yandex.ru/referats">Яндекс.Рефераты</a>.</h2>
Зачем здесь h2?

2016-11-08 09:01 UTC, mokhov commented on index.css
> +.imgAnalyzing
В вебе не принято писать camelCase, а принято писать через дефисы

2016-11-08 16:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-15 09:37 UTC, closed without merging