Смеловская Татьяна
urfu-2016/markup-task-4 pull request #24
Opened 2016-10-30 13:06 UTC by TatianaSmelovsckaya

2016-10-30 13:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 06:06 UTC, bazhenova commented
Привет. Сначала пройдемся по требованиям. Некоторые отсутствуют:
```
1) Есть, конечно, картинки и подписи к ним, иногда они занимают несколько! колонок
2) Изредка текст пишут:
В
О
Т

Т
А
К
```

2016-11-01 06:07 UTC, bazhenova commented on index.css
> +    padding: 1rem 4rem;
почему ты везде используешь `rem`?

2016-11-01 06:24 UTC, bazhenova commented
🍅

2016-11-01 08:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 08:26 UTC, TatianaSmelovsckaya commented on index.css
> +    padding: 1rem 4rem;
Rem позволяет изменять необходимые характеристики относительно только одной величины. Кажется, что это удобнее, так как не нужно задумываться о том, какие ещё свойства могут повлиять на значение с rem. Поэтому и выбрала его)

2016-11-01 08:28 UTC, TatianaSmelovsckaya commented
🍏

2016-11-01 18:56 UTC, bazhenova commented on index.css
> +    font-family: serif;
Давай оптимизируем написание правил. Это я сейчас про `font-family` и `font-size`. Давай вспомним про свойство `font`. Тогда и число строчек уменьшится)

2016-11-01 18:56 UTC, bazhenova commented on index.css
> +    float: left;
Зачем тут `float`?

2016-11-01 18:56 UTC, bazhenova commented on index.css
> +    font-family: serif;
Посмотри еще в остальном коде

2016-11-01 19:00 UTC, bazhenova commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Russo+One&amp;subset=cyrillic" rel="stylesheet">
Давай хотя бы один шрифт подключим самостоятельно. Вам рассказывали на лекции, как (подсказка: font-face)

2016-11-01 19:02 UTC, bazhenova commented
Кажется потерялась колоночность в Firefox. Давай ее найдем)
![image](https://cloud.githubusercontent.com/assets/12410663/19903217/a22f8c70-a08f-11e6-9aaa-7bf6ea1d54e7.png)

2016-11-01 19:03 UTC, bazhenova commented
🍅

2016-11-02 06:59 UTC, TatianaSmelovsckaya commented on index.css
> +    float: left;
Для позиционирования. Убрать/исправить?

2016-11-02 07:07 UTC, bazhenova commented on index.css
> +    float: left;
Пока в данной задаче `float` не надо использовать. Да, лучше сделать по-другому. Ну и как-нибудь получше расположить текст, а то он ухудшает вид газеты) Можно опустить его пониже, чтобы он сильно вверх не торчал.

2016-11-02 08:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-02 08:02 UTC, TatianaSmelovsckaya commented
🍏

2016-11-05 04:09 UTC, bazhenova commented on index.css
> +/*
зачем тут оставлены комментарии?

2016-11-05 04:11 UTC, bazhenova commented
Привет. Лучше не оставлять такие комментарии в коде) А так передаю тебя ментору.

2016-11-05 04:11 UTC, bazhenova commented
🚀

2016-11-05 07:57 UTC, TatianaSmelovsckaya commented on index.css
> +/*
Ой, это не должно было остаться. Естественно, эти комментарии нужно удалить, забыла(

2016-11-05 08:14 UTC, bazhenova commented on index.css
> +/*
Да ничего, это на будущее)

2016-11-07 09:58 UTC, forshtreter commented
Таня, привет. В целом очень даже неплохо, мне нравится. Но раз уж ты все равно будешь убирать комментарии, накидаю ещё пару замечаний.

2016-11-07 13:47 UTC, forshtreter requested changes
🍅

2016-11-07 13:47 UTC, forshtreter commented on index.html
> +            <h3 class="info">В С Я</h3>
Изящное решение с вертикальным текстом, мне нравится. Но столько h3 подряд – всё-таки перебор, лучше заменить на ничего не значащие спаны в данном случае. Также по желанию можно попробовать избавиться от пробелов.

2016-11-07 13:47 UTC, forshtreter commented on index.html
> +        <h1 class="newspaper-name">ИСКУССТВО ЛЕВИТАЦИИ</h1>
Хочется сделать буквы заглавными с помощью CSS

2016-11-07 13:47 UTC, forshtreter commented on index.html
> +                    вни&shy;ма&shy;ние из ря&shy;да вон вы&shy;хо&shy;дя&shy;щий ге&shy;до&shy;низм.
Хочется отбить содержимое ещё одним табом, а то всё сливается и не видно где заканчивается один параграф и начинается следующий

2016-11-07 13:47 UTC, forshtreter commented on index.html
> +                <div class="any-news-text">
Кажется, от any-news-text можно запросто избавиться, тем более что ты используешь nth-of-type, а не nth-child

2016-11-07 13:47 UTC, forshtreter commented on index.css
> +.any-news-paragraph
В общем и целом использование классов – это очень правильно и хорошо. Но тут речь о параграфах текста, которые в реальной жизни как правило прилетают из всяких админок и wysiwyg редакторов и проставить им классы возможности нет. Опять же, если тут написать .any-news-text p, то связь с [вот этим](https://github.com/urfu-2016/markup-task-4/pull/24/files#diff-bca1542f88ef8253c16b452e9ad09f98R146) селектором станет более явной.

2016-11-07 15:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 15:03 UTC, TatianaSmelovsckaya commented
Доброго вечера!
Все замечания исправила (от пробелов тоже избавилась, стало приятней).
От any-news-text действительно можно избавиться, по началу не заметила этого.

2016-11-07 15:03 UTC, TatianaSmelovsckaya commented
🍏

2016-11-11 12:59 UTC, forshtreter commented
Всё хорошо, принимаю

2016-11-11 12:59 UTC, closed without merging