Квашнина Ульяна
urfu-2016/markup-task-4 pull request #29
Opened 2016-10-30 16:25 UTC by Uliana1997

2016-10-30 16:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:34 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 17:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 17:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 17:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-31 05:20 UTC, Mokoshka commented
Что-то пошло не так) (Яндекс Браузер)
![image](https://cloud.githubusercontent.com/assets/14892550/19844918/90c8f06c-9f53-11e6-8525-54617d611bb4.png)

2016-10-31 05:21 UTC, Mokoshka commented
Наверное, красные буквы должны быть на две строки, или так и задумано?
![image](https://cloud.githubusercontent.com/assets/14892550/19844934/b9e0466c-9f53-11e6-8716-4f68a031f69c.png)

2016-10-31 05:33 UTC, Mokoshka commented on index.html
> +                <p>Ху&shy;до&shy;же&shy;ствен&shy;ная кон&shy;та&shy;ми&shy;на&shy;ция, не вда&shy;ва&shy;
Такие переносы строк приводят вот к таким результатам
![image](https://cloud.githubusercontent.com/assets/14892550/19845092/6207409c-9f55-11e6-9187-4c67ed4c5607.png)

2016-10-31 05:40 UTC, Mokoshka commented on index.css
> +    src: local(italyb)
Почему не в одну строку? Ну или хотя бы не переносить запятые, чтобы они не были в начале строк

2016-10-31 05:40 UTC, Mokoshka commented on index.css
> +    background-size: 10px, 10px;
background-size: 10px;

2016-10-31 05:42 UTC, Mokoshka commented on index.html
> +    <h2>«Деструктивный метод кластерного анализа: основные моменты»</h2>
тут кажется отступа не хватает

2016-10-31 05:45 UTC, Mokoshka commented on index.html
> +        <div class="cat"><img src="bla.png" alt="*"></div>
Хотелось бы более осмысленный текст в alt. И
```
<div class="cat">
    <img src="bla.png" alt="*">
</div>
```

2016-10-31 05:46 UTC, Mokoshka commented on index.html
> +                ет комплекс апри&shy;ор&shy;ной бисек&shy;су&shy;аль&shy;но&shy;сти.</p>
А вот здесь лишний отступ

2016-10-31 05:47 UTC, Mokoshka commented on index.html
> +            </figure>
Тоже лишние отступы

2016-10-31 05:49 UTC, Mokoshka commented on index.css
> +    column-count: 2;
Безвендорное правило всегда идет после правил с вендорными префиксами

2016-10-31 05:50 UTC, Mokoshka commented on index.css
> +    border: 1px solid black;
Сначала задаешь border-style, а потом переопределяешь его в border. Как-то это неправильно

2016-10-31 05:51 UTC, Mokoshka commented on index.css
> +    column-count: 3;
Опять же неверный порядок правил

2016-10-31 05:52 UTC, Mokoshka commented on index.css
> +    column-count: 3;
А здесь почему без префикса?

2016-10-31 05:53 UTC, Mokoshka commented on index.css
> +    border-radius: 100px;
Неверный порядок правил

2016-10-31 05:57 UTC, Mokoshka commented
В Firefox немножко разъехалось
![image](https://cloud.githubusercontent.com/assets/14892550/19845414/844d400e-9f58-11e6-9eb4-facbcc470eaa.png)

2016-10-31 06:00 UTC, Mokoshka commented
🍅

2016-11-03 17:51 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-03 17:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 16:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 16:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 17:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 17:15 UTC, Uliana1997 commented
🍏

2016-11-06 09:04 UTC, Mokoshka commented on index.css
> +    max-width: 700px;
Иногда можно разделять группы правил пустыми строками. Так можно разделять правила  на блоки, например блок правил для шрифтов, блок правил для текста, блок правил для декоративного оформления и т.д.
Это на будущее, чтобы проще было читать css код.

2016-11-06 09:07 UTC, Mokoshka commented on index.css
> +    border: 1px solid grey;
Цвет лучше указывать hex-кодом

2016-11-06 09:07 UTC, Mokoshka commented on index.css
> +    float: right;
А зачем здесь float?

2016-11-06 09:10 UTC, Mokoshka commented on index.css
> +    font-size: 20px;
Попробуй использовать единицу измерения em для увеличения шрифта буквы пропорционально

2016-11-06 09:13 UTC, Mokoshka commented
Появился горизонтальный скролл, он здесь немного неуместен
![image](https://cloud.githubusercontent.com/assets/14892550/20036188/990ba5b6-a422-11e6-8e99-3578c79989e1.png)

2016-11-06 09:20 UTC, Mokoshka commented
- Давай сделаем разметку немного лучше: в параграфах, в которых много текста, добавим вложенность 
```
<p>
    Много текста
</p>
```
- И немного улучшим картинки: для всех картинок добавим атрибут title
- Первые буквы так и должны быть размером полторы строки?

2016-11-06 09:22 UTC, Mokoshka commented
🍅

2016-11-06 13:24 UTC, Uliana1997 commented on index.css
> +    font-size: 20px;
Я не знаю, я просто увеличила размер первой буквы, не задумывалась во сколько раз ее делать больше, но спасибо за классные советы)

2016-11-06 13:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 13:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 13:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 13:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 13:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 13:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 13:49 UTC, Uliana1997 commented
🍏

2016-11-06 15:15 UTC, Mokoshka commented on index.css
> +    overflow-x: hidden;
Помогло, но лучше разобраться почему так получилось. Скорее всего из-за float где-то

2016-11-06 15:15 UTC, Mokoshka commented on index.css
> +    border: 1px solid black;
hex-код

2016-11-06 15:15 UTC, Mokoshka commented on index.css
> +    border-bottom: 2px solid black;
hex-код

2016-11-06 15:15 UTC, Mokoshka commented on index.css
> +    border-bottom: 2px solid black;
hex-код

2016-11-06 15:15 UTC, Mokoshka commented on index.css
> +    border-bottom: 1px solid black;
hex-код

2016-11-06 15:16 UTC, Mokoshka commented on index.css
> +    border-bottom: 1 px solid black;
hex-код

2016-11-06 15:16 UTC, Mokoshka commented on index.css
> +    border-bottom: 1px solid black;
hex-код

2016-11-06 15:18 UTC, Mokoshka commented on index.html
> +        <div class="first_article">
Классы лучше именовать через дефис - `first-article`

2016-11-06 15:19 UTC, Mokoshka commented
Исправь цвета и названия классов и передам задачу ментору

2016-11-06 15:19 UTC, Mokoshka commented
🍅

2016-11-06 16:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 16:43 UTC, Uliana1997 commented
🍏

2016-11-06 16:43 UTC, Uliana1997 commented
все цвета исправила и классы

2016-11-06 17:54 UTC, Mokoshka commented
🚀

2016-11-07 10:59 UTC, forshtreter commented
Привет, Ульяна. Замечаний много, так что пока что 🍅 , но время ещё есть :)

2016-11-07 17:39 UTC, Uliana1997 commented
А можно список конкретных замечаний, я все поправлю 

Отправлено с iPhone

> 7 нояб. 2016 г., в 15:59, forshtreter <notifications@github.com> написал(а):
> 
> Привет, Ульяна. Замечаний много, так что пока что 🍅 , но время ещё есть :)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-11-11 13:13 UTC, forshtreter requested changes

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    overflow-x: hidden;
Согласен, разобраться надо обязательно, `overflow-x` на body - не вариант, на узком экране человек просто не увидит часть содержимого.

2016-11-11 13:13 UTC, forshtreter commented on index.html
> +        <div class="cat"><img src="bla.png" alt="Стикер кота, говорящего бла-бла" title="Котик бла-бла"></div>
Какой-то неуместный кот, честно говоря, и занимает целую строку :)

2016-11-11 13:13 UTC, forshtreter commented on index.html
> +            <div class="first">
Избыточная разметка, можно обойтись без этого дива.

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    font-size: 70px;
Стоит объединить в font

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    text-transform: uppercase;
А вот за это жирный плюс, все кого смотрел до этого – писали капсом в HTML :)

2016-11-11 13:13 UTC, forshtreter commented on index.html
> +            «Почему традиционен интеграл от функции комплексной переменной?»
Текст с Яндекс.Рефератов, а слово state очень многозначное, поэтом я не могу понять, хорошо ли размечен этот блок. Это цитата? Или просто некий выделенный текст?

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    display: block;
Поскольку тут float, то display: block не нужен

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    font-family: Georgia, 'Times New Roman', serif;
Тоже вполне можно объединить font

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +.centered
От презентационных классов centered, left и right стоит избавиться в пользу более осмысленных, потому что если вдруг где-то это центрирование нужно будет убрать, то придется выколупывать классы из html вместо того, чтобы поправить одну строчку в css

2016-11-11 13:13 UTC, forshtreter commented on index.css
> +    border-style: 2px, double;
Невалидное правило

2016-11-11 13:15 UTC, forshtreter commented
Ох блин. Я дико извиняюсь, запутался в интерфейсе гитхаба, замечания зависли в статусе pending, а я только сейчас это заметил. Дедлайн вышел, но тут моя ошибка, так что в случае чего полбалла можно будет оспорить без проблем

2016-11-14 15:16 UTC, forshtreter commented
🍅

2016-11-22 16:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-22 16:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-22 16:49 UTC, Uliana1997 commented
:green_apple:

2016-12-04 18:16 UTC, closed without merging