Кондрашин Дмитрий
urfu-2016/markup-task-4 pull request #34
Opened 2016-10-30 19:38 UTC by dkondrashin

2016-10-30 19:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-31 15:40 UTC, onufrienko commented
Привет!
Так и задумано?
![image](https://cloud.githubusercontent.com/assets/14929766/19860222/c4ea9d04-9fa9-11e6-87f5-94e3bd984b09.png)
При ресайзе окна:
![image](https://cloud.githubusercontent.com/assets/14929766/19860314/1465b170-9faa-11e6-97c9-b277a350b938.png)
Ну и заголовок все-таки, может, обойдется без таких слов? :)
![image](https://cloud.githubusercontent.com/assets/14929766/19860332/21676080-9faa-11e6-913d-5b25ecabd871.png)

2016-10-31 15:43 UTC, onufrienko commented on index.html
> +        <p class="first">
first что?

2016-10-31 15:44 UTC, onufrienko commented on index.html
> +            Вот что он написал в своем инстаграме о <span class="young">Дмитрии Попове</span>, который
young что?

2016-10-31 15:45 UTC, onufrienko commented on index.html
> +            «<span class="young">Сашка Никитин</span>. <span class="club">«Рубин»</span>
опять-таки young

2016-10-31 15:45 UTC, onufrienko commented on index.html
> +                    </p>
Тег куда-то уехал

2016-10-31 15:46 UTC, onufrienko commented on index.html
> +    В
Отступов не хватает

2016-10-31 15:47 UTC, onufrienko commented on index.html
> +            <img class="imgCenter" src="http://s12.radikal.ru/i185/1610/65/0c58d8425ee9.jpg" alt="Дзюбиньо">
не хватает атрибута title

2016-10-31 15:49 UTC, onufrienko commented on index.html
> +            <img class="imgCenter" src="http://s019.radikal.ru/i644/1610/fc/f8f901dd5fde.jpg" alt="Попов">
Здесь тоже нужен атрибут title

2016-10-31 15:52 UTC, onufrienko commented on index.html
> +            <img class="imgCenter" src="http://s018.radikal.ru/i513/1610/9b/7ccc80ba08f2.jpg" alt="Мордовия">
не хватает атрибута title

2016-10-31 15:52 UTC, onufrienko commented on index.html
> +        </div>
что-то не то с отступами

2016-10-31 15:53 UTC, onufrienko commented
Неплохо бы так же использовать спец. символы

2016-10-31 15:53 UTC, onufrienko commented
Хорошо, что ты используешь теги вроде footer'а, header'а и т.п.

2016-10-31 15:55 UTC, onufrienko commented on index.css
> +.imgCenter
Используй "-" в качестве вместо того, чтобы писать селекторы в camelCase

2016-10-31 15:57 UTC, onufrienko commented on index.css
> +    float: right;
В этом задании нельзя использовать плавающие элементы.

2016-10-31 15:57 UTC, onufrienko commented on index.css
> +    float: left;
Ай-яй-яй, нельзя!

2016-10-31 15:58 UTC, onufrienko commented
Было бы хорошо использовать в тексте переносы, тогда бы текст здесь:
![image](https://cloud.githubusercontent.com/assets/14929766/19861030/ce27a288-9fac-11e6-8644-03f81caf8d82.png)
выглядел приятнее

2016-10-31 15:59 UTC, onufrienko commented
Не вижу, чтобы было выполнено условие "Первая буква первого параграфа в статье обычно заметно выделяется"

2016-10-31 16:00 UTC, onufrienko commented on index.css
> +div.mainArticle
опять-таки camelCase не должен быть

2016-10-31 16:01 UTC, onufrienko commented on index.css
> +div.mainArticle
почему ты делаешь именно такой селектор, а не просто класс?

2016-10-31 16:02 UTC, onufrienko commented on index.css
> +pre
давай-ка дадим элементу класс и будем обращаться к нему не по тегу

2016-10-31 16:03 UTC, onufrienko commented on index.css
> +    font-size: 100px;
font-size и font-family можно объединить в font

2016-10-31 16:04 UTC, onufrienko commented
Неплохо было подключать шрифты и с расширением woff

2016-10-31 16:05 UTC, onufrienko commented
В целом, будет хорошо, если газета будет выглядеть чуточку аккуратнее

2016-10-31 16:05 UTC, onufrienko commented
:tomato:

2016-10-31 16:29 UTC, onufrienko commented
Будет еще хорошо заюзать атрибут local у шрифтов

2016-11-04 20:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 16:26 UTC, onufrienko commented
так лучше :D
![image](https://cloud.githubusercontent.com/assets/14929766/20031757/b161a9fc-a38d-11e6-9129-100ec765a4f1.png)

2016-11-05 16:27 UTC, onufrienko commented on index.css
> +        , url(fonts/FasterOne-Regular.ttf)
зачем запятые переносишь? :о

2016-11-05 16:27 UTC, onufrienko commented on index.css
> +    font-family: Prosto One;
Оригинальный шрифт так и называется?

2016-11-05 16:28 UTC, onufrienko commented on index.html
> +                <img class="img-center" src="http://s12.radikal.ru/i185/1610/65/0c58d8425ee9.jpg"
где title?

2016-11-05 16:31 UTC, onufrienko commented
firefox без колонок:
![image](https://cloud.githubusercontent.com/assets/14929766/20031805/7283b7ba-a38e-11e6-85f9-a7717a955c4d.png)

2016-11-05 16:32 UTC, onufrienko commented
🍅

2016-11-05 18:42 UTC, dkondrashin commented on index.css
> +        , url(fonts/FasterOne-Regular.ttf)
Потому что линтер не пропускает иначе

2016-11-05 18:42 UTC, dkondrashin commented on index.css
> +    font-family: Prosto One;
Да, вот он
https://fonts.google.com/?query=prosto&selection.family=Prosto+One

2016-11-05 19:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 11:59 UTC, onufrienko commented
:rocket:

2016-11-08 20:23 UTC, maxvipon requested changes
Прошу прощения, я вчера написал комментов, а кнопку "Submit review" не нажал – давненько не заходил на гихаб, как-то упустил сие новшество.

2016-11-08 20:23 UTC, maxvipon commented on index.html
> +        <div class="main-article">
Зачем этот див? Просто `<article>` не достаточно?

2016-11-08 20:23 UTC, maxvipon commented on index.html
> +        <div class="facts">
Аналогично 👆

2016-11-09 07:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-09 07:55 UTC, maxvipon approved these changes
🆗

2016-11-09 07:55 UTC, closed without merging