Грехов Кирилл
urfu-2016/markup-task-4 pull request #46
Opened 2016-10-31 12:35 UTC by Grehhov

2016-10-31 12:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 12:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 12:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 12:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 12:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 04:52 UTC, Mokoshka commented on index.css
> +    src: url(https://fonts.gstatic.com/s/lobster/v18/c28rH3kclCLEuIsGhOg7evY6323mHUZFJMgTvxaG2iE.woff2);
А если в моем браузере не будет поддерживаться woff2?

2016-11-01 04:54 UTC, Mokoshka commented on index.css
> +    background: lightgoldenrodyellow;
Цвета лучше задавать через hex-код

2016-11-01 04:55 UTC, Mokoshka commented on index.css
> +    color: dodgerblue;
hex-код

2016-11-01 04:55 UTC, Mokoshka commented on index.css
> +    column-rule: solid 1px lightgrey;
hex-код

2016-11-01 04:55 UTC, Mokoshka commented on index.css
> +    text-shadow: 2px 2px 2px black;
hex-код

2016-11-01 04:56 UTC, Mokoshka commented on index.css
> +    text-shadow: 1px 1px 5px grey;
hex-код

2016-11-01 04:56 UTC, Mokoshka commented on index.css
> +    color: gray;
hex-код

2016-11-01 04:56 UTC, Mokoshka commented on index.css
> +    border: solid 1px gray;
hex-код

2016-11-01 04:56 UTC, Mokoshka commented on index.css
> +    color: red;
hex-код

2016-11-01 04:56 UTC, Mokoshka commented on index.css
> +    border-top: dotted 2px red;
hex-код

2016-11-01 04:58 UTC, Mokoshka commented on index.css
> +blockquote:before
Селекторы с одними и теми же правилами прописываются через запятую

2016-11-01 04:58 UTC, Mokoshka commented on index.css
> +    color: gray;
hex-код

2016-11-01 04:58 UTC, Mokoshka commented on index.css
> +    border: dotted 2px blue;
hex-код

2016-11-01 04:58 UTC, Mokoshka commented on index.css
> +    border-left: dotted 2px red;
hex-код

2016-11-01 05:01 UTC, Mokoshka commented on index.css
> +    float: right;
Подумай, как можно написать, не используя float

2016-11-01 05:01 UTC, Mokoshka commented on index.css
> +    border-bottom: dotted 2px red;
hex-код

2016-11-01 05:07 UTC, Mokoshka commented on index.html
> +        <div>- Кулидж Калвин</div><hr>
Используй спецсимволы для "-"

2016-11-01 05:09 UTC, Mokoshka commented on index.html
> +        <article>
Тут ненужная вложенность div > article

2016-11-01 05:13 UTC, Mokoshka commented
Упс (Firefox)
![image](https://cloud.githubusercontent.com/assets/14892550/19880091/be5be4d0-a01b-11e6-9c71-facb87e57126.png)

2016-11-01 05:19 UTC, Mokoshka commented
По оформлению: красные и синие пунктирные границы выглядят дико
По коду: 
 - Не соблюдена семантика кода. Можно использовать такие теги, как main  и section, которые сделают код семантичнее. Подумай, как можно улучшить твой код.
- Цвета нужно задавать hex-кодом
- Придумать как решить задачу без использования float

2016-11-01 05:20 UTC, Mokoshka commented
🍅

2016-11-05 19:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 19:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 19:39 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 19:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 19:44 UTC, Grehhov commented on index.html
> +        <article>
Эта вложенность нужна, чтобы главная статья была отдельно, а остальные статьи при этом шли друг за другом.

2016-11-05 19:46 UTC, Grehhov commented
🍏

2016-11-06 09:24 UTC, Mokoshka commented
Вроде это не начало абзаца, а тире красное
![image](https://cloud.githubusercontent.com/assets/14892550/20036233/4f9d9a86-a424-11e6-908d-461b5d258756.png)

2016-11-06 09:27 UTC, Mokoshka commented on index.css
> +    display: flex;
Круто, конечно, что ты знаешь про flex, но эту задачу нужно решить, не используя его. Использовать нужно то, что рассказывали на лекциях.

2016-11-06 09:27 UTC, Mokoshka commented on index.css
> +    -webkit-column-rule: solid 1px #d3d3d3;
Безвендорное правило должно находиться после правил с вендорными префиксами

2016-11-06 09:29 UTC, Mokoshka commented on index.html
> +            Завтра<br>
От br нужно избавиться. Попробуй сверстать так же, не используя его

2016-11-06 09:29 UTC, Mokoshka commented on index.html
> +                <img src="pic1.jpg" alt="Баскетболистки УГМК"><br>
И тут от br нужно избавиться

2016-11-06 09:33 UTC, Mokoshka commented
- flex убрать, потом будет задача, где надо будет использовать только flex, но пока что нужно верстать, используя знания из лекций
- Поправить разметку, чтобы не использовались br
- Добавить подключение шрифта вручную, используя @font-face. Желательно использовать несколько расширений, но обязательно должен быть woff

2016-11-06 09:34 UTC, Mokoshka commented
🍅

2016-11-06 20:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 20:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 20:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 20:43 UTC, Grehhov commented
🍏

2016-11-07 05:47 UTC, Mokoshka commented
🚀

2016-11-07 09:16 UTC, VorontsovMaxim requested changes
🍅 
В целом хорошо, есть совсем немного замечаний

2016-11-07 09:16 UTC, VorontsovMaxim commented on index.css
> +    flex: 1 100%;
В этом задании можно обойтись без `flex`, тем более непонятно зачем он здесь тебе

2016-11-07 09:16 UTC, VorontsovMaxim commented on index.css
> +    font-family: 'Ruslan Display', cursive;
Эти два правила `font-...` можно объединить

2016-11-07 09:16 UTC, VorontsovMaxim commented on index.css
> +    flex: 1 100%;
Аналогично про `flex`

2016-11-07 09:16 UTC, VorontsovMaxim commented on index.html
> +                <span>Баскетбольный клуб устроил праздник для фанатов</span>
Для картинок с подписями можно использовать `<figcaption>`

2016-11-07 09:16 UTC, VorontsovMaxim commented on index.html
> +                <span>Баскетбольный клуб устроил праздник для фанатов</span>
К картинкам с подписями ниже это тоже применимо

2016-11-07 10:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 10:14 UTC, Grehhov commented on index.css
> +    flex: 1 100%;
Он не нужен ни здесь, ни в футере. Я просто забыл его убрать оттуда

2016-11-07 10:14 UTC, Grehhov commented
🍏

2016-11-07 16:35 UTC, VorontsovMaxim commented
1. Когда я писал про `<figure>` и `<figcaption>` я имел ввиду, что и в html тоже нужно изменить, иначе твои правки не имеют ниакакого смысла. Стили применяются к `<img>` внутри `<figure>`, но таких у тебя вообще нет. Это нужно переделать

2. Еще хотелось бы, чтобы вместо селекторов по тегам, всем элементам ты дал классы соответствующие смыслу элементов.
Во-первых, так css будет понятнее
Во-вторых, может в данном проекте это и не критично, но когда ты столкнешься с проектами побольше, где стили будут например в нескольких файлах, ты поймешь, что селекторы по тегу это не самый грамотный подход, потому что задавая их по тегу, ты можешь повлиять на те элементы к которым эти стили и не должны вовсе применяться. Поэтому лучше сразу привыкать использовать классы

2016-11-07 16:35 UTC, VorontsovMaxim commented
🍅

2016-11-07 16:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 16:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 16:52 UTC, Grehhov commented
🍏

2016-11-07 16:53 UTC, VorontsovMaxim commented
Принято

2016-11-07 16:53 UTC, closed without merging