Цветкова Валерия
urfu-2016/markup-task-4 pull request #47
Opened 2016-10-31 14:02 UTC by ValeriaTsvetkova

2016-10-31 14:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +<header class="mainHeader">The New York Times</header>
Имена классов css обычно пишутся через дефис (-). Не используй camelCase

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +    <select class="leftSelect" onchange="document.getElementById('body').style.fontFamily = value">
В описании к дополнительному заданию жирным шрифтом выделена информация, что js использовать не надо :)

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +    <section class="column3">
Что значит column3?

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +                <img src="pictures/1.jpg">
Нужно добавить всем картинкам title. Значение alt должно отвечать на вопрос «Что изображено на картинке?»

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +        <h3 class="multiColumnHead">Science</h3>
У тебя тут заголовок 3го уровня, но нигде нет заголовков уровня 1 и 2

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +            <header class="multiColumnHead">A Scaredy-Cat’s Investigation Into Why People Enjoy Fear</header>
Тег `<header>` не подходит для заголовка статьи. Пересмотри лекцию по HTML

Аналогично с тегом `<footer>`

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +    <div class="column4">
В именах селекторов можно использовать только `a-z` и `-`

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +            <p class="firstParagraph">Halloween is here again. That means your co-workers have planted
Посмотри в конце гайда про форматирование https://github.com/urfu-2016/guides/blob/master/codestyle/html.md

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.html
> +            <p>For many, being scared is a jolting escape from daily life. When immersed in a scary
Нет закрывающего тега

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +@font-face
Шрифты должны подключаться в начале файла. Почитай об этом в лекции Олега про шрифты и текст

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: Libre_Baskerville;
Стоит указать шрифт или общее семейство шрифтов, которые браузер подключит, если не загрузится Libre_Baskerville

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    margin-left: 15px;
margin-left и margin-right можно объединить

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    margin-left: 0;
лишнее

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    float: left;
float для разметки не используем в этой задаче

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: Lobster_Two;
font-family и font-size можно объединить

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    border-color: #000;
DRY

2016-11-04 06:57 UTC, Victoria-Vladimirova commented on index.css
> +    margin: 0;
лишнее

2016-11-04 06:58 UTC, Victoria-Vladimirova commented
В firefox твоя газета развалилась

![2016-11-03 10 27 04](https://cloud.githubusercontent.com/assets/14944973/19997095/ee1e462e-a285-11e6-8f37-c8c72de4413d.png)

2016-11-04 07:00 UTC, Victoria-Vladimirova commented
🍅

2016-11-04 18:10 UTC, Victoria-Vladimirova commented
Еще в задании говорится, что в тексте используются переносы. У тебя их нет

2016-11-05 12:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 12:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 12:38 UTC, ValeriaTsvetkova commented
Оставила один float для вертикального текста, чтоб он был обтекаемым, и не добавила закрывающийся тег <p> (не проходит линтинг).

2016-11-05 12:41 UTC, ValeriaTsvetkova commented
:green_apple:

2016-11-05 12:49 UTC, Victoria-Vladimirova commented
@ValeriaTsvetkova Почему падает тест с закрывающим тегом? Какое сообщение?

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.html
> +    <h2>Science</h2>
Предлагаю сделать 3 секции (`<section>`) - Science, Technology, Travel, внутри которых будет заголовок и статьи, каждая из которых внутри своего `<article>`

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.html
> +        <section class="four-column">
Почему ты делишь всю газету из 8ми колонок на 4 колонки + 4 колонки?

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.html
> +        <h2 class="breaking-word">Technology</h2>
Лучше что-то вроде section-vertical-header

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.html
> +                “We wanted to help people pre&shy;pare for the elec&shy;tion and make it as easy as
Здесь не хватает `<q>` и еще в некоторых местах

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.html
> +                Black&shy;out, Mr. Ran&shy;dall said: <blockquote>For a fi&shy;nite peri&shy;od of time,
`<blockquote>` не может находится внутри `<p>`. Поэтому у тебя проблемы с закрывающим тегом)
Сейчас браузер закрывает тег `<p>` после "Mr. Ran&shy;dall said:"

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.css
> +footer
ты же убрала footer :)

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.css
> +    src: url('fonts/Lobster_Two/LobsterTwo-Bold.ttf');
Предпочтительный формат woff, так как загружается быстрее, чем ttf.
Хорошо еще подключить woff2 и eot

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.css
> +    column-count: 2;
Безвендорное правило должно идти после правил с вендорными префиксами

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.css
> +    margin-bottom: .4em;
объединить с margin-top

2016-11-05 15:36 UTC, Victoria-Vladimirova commented on index.css
> +    background-color: beige;
Лучше указывать код цвета. Здесь `#f5f5dc`
http://www.w3schools.com/colors/colors_names.asp

2016-11-05 15:38 UTC, Victoria-Vladimirova commented
Когда выбираю Bigger, появляются проблемы:
1)  ![2016-11-05 20 34 32](https://cloud.githubusercontent.com/assets/14944973/20031342/b7d76e98-a397-11e6-83a4-5bee9de65392.png)

2) ![2016-11-05 20 34 54](https://cloud.githubusercontent.com/assets/14944973/20031347/c92e97ac-a397-11e6-95e7-473340c995b0.png)

2016-11-05 15:44 UTC, Victoria-Vladimirova commented
🍅

2016-11-06 13:28 UTC, ValeriaTsvetkova commented on index.html
> +                Black&shy;out, Mr. Ran&shy;dall said: <blockquote>For a fi&shy;nite peri&shy;od of time,
Поняла, спасибо :)

2016-11-06 13:31 UTC, ValeriaTsvetkova commented on index.html
> +        <section class="four-column">
Я вообще всю страницу делю на две колонки, а потом каждую на 4, чтобы сделать картинку через все колонки и не использовать column-span: all.

2016-11-06 13:33 UTC, ValeriaTsvetkova commented on index.html
> +    <h2>Science</h2>
Тогда лучше заменить h2 на header или можно так оставить?

2016-11-06 13:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 13:36 UTC, ValeriaTsvetkova commented
:green_apple:

2016-11-06 16:29 UTC, Victoria-Vladimirova commented on index.html
> +    <h2>Science</h2>
Здесь вполне достаточно только заголовка (h2)

2016-11-06 17:07 UTC, Victoria-Vladimirova reviewed
Еще немного замечаний

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +    font: 3em Lobster_Two;
а здесь нет семейства шрифтов :с

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +    -moz-column-count: 4;
```
-moz-column-count: 4;
-webkit-column-count: 4;
column-count: 4;
-moz-column-rule: 2px solid #000;
-webkit-column-rule: 2px solid #000;
column-rule: 2px solid #000;
```

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: Architects_Daughter, cursive;
вместо `font-family` и `font-size` можно писать одну строку `font`

```
   font: .9em Architects_Daughter, cursive;
```

Ниже по коду аналогично надо заменить

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +    src: url('fonts/Lobster-Two/Lobster-Two-700.woff')
Так будет понятнее

```
   src: url('fonts/Lobster-Two/Lobster-Two-700.woff') format('woff'),
        url('fonts/Lobster-Two/Lobster-Two-700.woff2') format('woff2'),
        url('fonts/Lobster-Two/Lobster-Two-700.eot') format('eot');
```

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +    font-size: 40px;
При переключении на более мелкий или крупный шрифт, этот размер меняться не будет

2016-11-06 17:07 UTC, Victoria-Vladimirova commented on index.css
> +figure img
Картинкам нужно указать ширину и высоту. 
Так браузер будет знать размер картинки и зарезервирует для неё место при загрузке страницы. Иначе компоновка страницы будет меняться во время загрузки.

2016-11-06 17:08 UTC, Victoria-Vladimirova commented
🍅

2016-11-07 00:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 00:23 UTC, ValeriaTsvetkova commented on index.css
> +    src: url('fonts/Lobster-Two/Lobster-Two-700.woff')
Да, я так пробовала, но с линтингом что-то не так. По-разному исправляла, но не помогло.
![image](https://cloud.githubusercontent.com/assets/22658416/20043142/7d257e12-a4a9-11e6-98ab-cb4ba831dedb.png)

2016-11-07 00:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 00:30 UTC, ValeriaTsvetkova commented
:green_apple:

2016-11-07 05:18 UTC, Victoria-Vladimirova commented on index.css
> +    src: url('fonts/Lobster-Two/Lobster-Two-700.woff')
Пробовала после запятых добавить пробел?

2016-11-07 05:36 UTC, Victoria-Vladimirova commented
🚀

2016-11-07 06:34 UTC, VorontsovMaxim requested changes
🍅 
В целом все хорошо, нужно только постараться избавиться от селекторов по тегам

2016-11-07 06:34 UTC, VorontsovMaxim commented on index.css
> +    src: url('fonts/Lobster-Two/Lobster-Two-700.woff')
Линтер действительно в этом случае себя странно ведет. Чтобы хоть как то исправить ситуацию можно написать например так:
```css
src: url('fonts/Lobster-Two/Lobster-Two-700.woff') format('woff')
   , url('fonts/Lobster-Two/Lobster-Two-700.woff2') format('woff2')
   , url('fonts/Lobster-Two/Lobster-Two-700.eot') format('eot');
```

2016-11-07 06:34 UTC, VorontsovMaxim commented on index.css
> +    border-width: 3px;
Можно сократить и написать одним правилом `border`

2016-11-07 06:34 UTC, VorontsovMaxim commented on index.css
> +hr
Элементам лучше давать классы, которые отражают их смысл
Конкретно в данной работе это может никак не сказаться, но в хоть немного большем проекте, где файлов со стилями > 1, это становится очень неудобно и непременно будут появляться ошибки
Поэтому лучше сразу привыкать

2016-11-07 06:34 UTC, VorontsovMaxim commented on index.css
> +    border-width: 1px;
1px - значение по умолчанию, можно не указывать

2016-11-07 06:34 UTC, VorontsovMaxim commented on index.css
> +    text-align: left;
`left` - значение по умолчанию, можно его не указывать

2016-11-07 10:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 10:56 UTC, ValeriaTsvetkova commented
Возник вопрос: нужно ли тегу main давать класс?
И не исправила селектор по тегу <p>. Нужно ли это тоже исправить? Не придумала, как это сделать оптимально.

2016-11-07 10:59 UTC, ValeriaTsvetkova commented
🍏

2016-11-07 16:43 UTC, VorontsovMaxim approved these changes

2016-11-07 16:44 UTC, VorontsovMaxim commented
Насчет `<p>` - конечно каждому параграфу не стоит давать класс, но можно было бы как нибудь отделить параграфы от вообще всех на странице. Например так: `.four-column p`
А вообще, теперь все хорошо!

2016-11-07 16:44 UTC, closed without merging