Кобяков Сергей
urfu-2016/markup-task-4 pull request #48
Opened 2016-10-31 14:13 UTC by skobyakov

2016-10-31 14:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on Kingthings_Foundation-webfont.svg
> +<?xml version="1.0" standalone="no"?>
Лучше все шрифты поместить в отдельную папку fonts

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.html
> +        <hr><hr>
Здесь не хватает переноса. 

А еще двойную полосу можно сделать одним hr :)

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.html
> +        <h4>Почему волнообразна кульминация?</h4><hr>
hr надо перенести

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.html
> +            <hr class="article">
Плохое название класса для горизонтальной линии. Она точно никакой не "article")

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.html
> +        <img src="photo.jpg" alt="Портрет">
Нужно добавить картинке title. 

Значение alt должно отвечать на вопрос «Что изображено на картинке?». В твоем случае это не совсем понятно. Надо написать хотя бы чей это портрет

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.css
> +    font-size: 150%;
почему тут проценты?

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.css
> +    text-transform: uppercase;
DRY

2016-11-01 05:58 UTC, Victoria-Vladimirova commented on index.css
> +    column-count: 4;
Безвендорное правило должно стоять после правил с вендорными префиксами

2016-11-01 06:00 UTC, Victoria-Vladimirova commented
Еще в задании говорится о подписи к картинкам, вертикальном тексте и о множестве необычных шрифтов.

2016-11-01 06:04 UTC, Victoria-Vladimirova commented
Картинка прижимается к левому краю и справа получается много пустого места. Её бы по центру выровнять

![2016-11-01 11 00 46](https://cloud.githubusercontent.com/assets/14944973/19880845/7bc096b4-a022-11e6-9696-c299ec36e7bc.png)

2016-11-01 06:06 UTC, Victoria-Vladimirova commented
🍅

2016-11-05 11:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-05 11:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 11:25 UTC, skobyakov commented
🍏

2016-11-05 16:19 UTC, Victoria-Vladimirova reviewed
Еще немного замечаний

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.html
> +            <p><img src="photo.jpg" alt="Фёдор Емельянович Буров" title="Фёдор Емельянович Буров"></p>
Зачем оборачивать картинку в `<p></p>`?

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.html
> +            <q>Польза от сего предмета не доказана, а вред весьма возможен.</q>
`<blockquote>`

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.html
> +
Тут пустая строка не нужна

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +    src: url('fonts/Veronica script Two.ttf');
Предпочтительный формат всё же woff. Остальные форматы можешь подключить дополнительно

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +
Тут пустая строка не нужна

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +    border-top: medium double black;
black -> #000
Лучше указывать hex-код цвета

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +    text-transform: uppercase;
`text-transform` и `text-align` ты указываешь для h4 и для h3. 
Можно объединить их
```
h3,
h4 
{
    text-transform: uppercase;
    text-align: center;
}
```

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +    font: bold  27px 'Astro_cyr-lat';
Укажи семейство шрифтов, которое будет подключено, если не загрузится этот шрифт

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +    margin: 0 auto;
Наверно, это должно было выровнять картинку, но ты применил их не к тому элементу :)

2016-11-05 16:19 UTC, Victoria-Vladimirova commented on index.css
> +.vertical-text-left
у vertical-text-left и vertical-text-right 3 свойства одинаковых. Можно объединить

2016-11-05 16:21 UTC, Victoria-Vladimirova commented
🍅

2016-11-06 15:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 15:57 UTC, skobyakov commented
🍏

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.css
> +.date
У h3 и h4 точно такие же 2 свойства написаны. Объедини date с ними.

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.html
> +            <h5>Взрыв как поле направлений</h5><hr>
hr нужно перенести на другую строку

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.css
> +.picture img
Картинкам нужно указать ширину и высоту. 
Так браузер будет знать размер картинки и зарезервирует для неё место при загрузке страницы. Иначе компоновка страницы будет меняться во время загрузки.

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: 'kingthings_foundationregular';
Называй семейство шрифтов как-то более читаемо. 'Kingthings Foundation'

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: 'Veronica script Two';
'Veronica Script Two'

2016-11-06 18:29 UTC, Victoria-Vladimirova commented on index.css
> +    font-family: 'Astro_cyr-lat';
'Astro'

2016-11-06 18:31 UTC, Victoria-Vladimirova commented
При сужении окна подпись уезжает вниз и вправо

![2016-11-06 23 28 26](https://cloud.githubusercontent.com/assets/14944973/20040424/fd4b005c-a478-11e6-9b93-78a10787f066.png)

2016-11-06 18:31 UTC, Victoria-Vladimirova commented
🍅

2016-11-06 18:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 19:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:04 UTC, skobyakov commented
🍏

2016-11-07 05:50 UTC, Victoria-Vladimirova commented on index.css
> +    width: 312px;
Так у тебя при сужении окна картинка не будет менять размер. 

Картинка будет выезжать за колонку: 
![2016-11-07 10 43 59](https://cloud.githubusercontent.com/assets/14944973/20047570/5c2ae584-a4d7-11e6-8f22-3958d98d0ee8.png)

Попробуй использовать другие единицы)

2016-11-07 05:50 UTC, Victoria-Vladimirova commented
🍅

2016-11-07 08:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 08:09 UTC, skobyakov commented
🍏

2016-11-07 12:43 UTC, Victoria-Vladimirova commented on index.css
> +    height: auto;
Это значение по умолчанию. Можно не указывать

2016-11-07 12:44 UTC, Victoria-Vladimirova commented
:rocket:

2016-11-08 08:50 UTC, mokhov requested changes
Почти всё хорошо, поправь минорные правки и приму задачу 🍅

2016-11-08 08:50 UTC, mokhov commented on index.css
> +    float: left;
Зачем тут float'ы?

2016-11-08 08:50 UTC, mokhov commented on index.html
> +            <h5>Взрыв как поле направлений</h5>
Почему сразу h5?

2016-11-08 08:50 UTC, mokhov commented on index.html
> +            <hr class="article-separator">
Почему нельзя было это же самое сделать стилями у article?

2016-11-08 10:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 10:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 10:23 UTC, skobyakov commented
🍏

2016-11-10 16:44 UTC, closed without merging