Филиппович Алексей
urfu-2016/markup-task-4 pull request #49
Opened 2016-10-31 14:16 UTC by Alex768

2016-10-31 14:17 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:24 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 14:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 20:31 UTC, hx0day commented
Шикарно сверстал, но стоит открыть в  Firefox 49
<img width="1381" alt="2016-11-02 1 28 22" src="https://cloud.githubusercontent.com/assets/4062420/19906286/f3c8df08-a09b-11e6-93e8-67c5e0bb7b7b.png">

2016-11-01 20:34 UTC, hx0day commented on index.html
> +                <img src="img/main-entry.jpg" alt="Спасение туриста на перевале Дятлова">
нужно заполнить атрибут title и задать атрибуты width и height у всех картинок

2016-11-01 20:36 UTC, hx0day commented on index.html
> +        <p class="date">31 октября 2016 года, Понедельник</p>
для дат и времени можно использовать тег `<time></time>`

2016-11-01 20:37 UTC, hx0day commented on index.html
> +        <h1 class="main-header">Спасатели на вертолёте эвакуировали
h1 на странице должен быть только оди

2016-11-01 20:39 UTC, hx0day commented on index.html
> +                    <img src="img/opera-1.jpg" alt="">
нужно заполнить атрибут title и задать атрибуты width и height у всех картинок
 @hx0day	Reply…

2016-11-01 20:39 UTC, hx0day commented on index.html
> +                    <img src="img/opera-2.jpg" alt="">
нужно заполнить атрибут title и задать атрибуты width и height у всех картинок
 @hx0day	Reply…

2016-11-01 20:40 UTC, hx0day commented on index.html
> +        <p>№23 (1052) 31 октября 2016г. | www.ngzt.ru, vk.com/ngztekb</p>
url думаю лучше сделать ссылкаи

2016-11-01 20:49 UTC, hx0day commented
Должны быть переносы в тексте и 
В
О
Т

Т
А
К

2016-11-01 20:49 UTC, hx0day commented
🍅

2016-11-01 21:24 UTC, hx0day commented on index.css
> +    float: right;
в этом задании нужно откзаться от woff

2016-11-01 21:26 UTC, hx0day commented on index.css
> +.main-entry p:first-child
можно объединить с .multicolumn h2:first-child и с .weather-today p
`
.weather-today p,
.multicolumn h2:first-child, 
.main-entry p:first-child {
...
}
`

2016-11-03 09:10 UTC, Alex768 commented on index.css
> +    float: right;
Вы про расширение файла шрифта?

2016-11-03 23:23 UTC, hx0day commented on index.css
> +    float: right;
да

2016-11-03 23:25 UTC, hx0day commented on index.css
> +    float: right;
Тут я наверное хотел написать другое, задачу нужно решать без float

2016-11-04 10:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 10:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 11:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 08:53 UTC, hx0day commented
<img width="1060" alt="2016-11-05 13 53 32" src="https://cloud.githubusercontent.com/assets/4062420/20028897/46792a26-a35f-11e6-8783-77cc85395f02.png">

2016-11-05 08:54 UTC, hx0day commented
🍅

2016-11-05 08:55 UTC, hx0day commented
пере-
но-
сов в тексте нет

2016-11-05 19:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:59 UTC, hx0day commented
Ты с Firefox 49 собираешься что-нибудь делать?

2016-11-07 06:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 06:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 16:12 UTC, hx0day commented
Последняя правка, Первая буква первого параграфа в статье обычно заметно выделяется

2016-11-07 16:15 UTC, hx0day commented
🍅

2016-11-07 16:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 17:00 UTC, hx0day commented
🚀

2016-11-08 19:24 UTC, steppefox requested changes
🍅

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    src: url('fonts/GothicRus.woff') format('woff'), url('fonts/GothicRus.ttf') format('truetype');
Пожалуйста, выровняй шрифты в столбик, а так же добавь директиву `local` для шрифта

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    height: auto !important;
Понимаю зачем этот хак, но в нем не будет необходимости, в случае если указывать у картинок корректный `height` и подставлять исходные картинки нормального (а не большого) размера.

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    overflow: hidden;
А вот это вот зачем?

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    column-count: 4;
Сначала должны идти вендорные правила `-moz`, `-webkit` и тд, а потом безвендорные, тоесть правильно:

```
-moz-column-count: 4;
-webkit-column-count: 4;
column-count: 4;

-moz-column-gap: 2em;
-webkit-column-gap: 2em;
column-gap: 2em;
```

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    overflow: hidden;
Зачем?

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    column-rule: none;
Тоже самое, неправильный порядок

2016-11-08 19:24 UTC, steppefox commented on index.css
> +    page-break-inside: avoid;
Тоже самое

2016-11-08 19:24 UTC, steppefox commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700&amp;subset=cyrillic"
Лучше перенести подключение шрифтов в css

2016-11-08 19:24 UTC, steppefox commented on index.html
> +        <p class="today">31 октября 2016 года, Понедельник</p>
Даты должны быть обернуты в соответсвующий тег даты

2016-11-08 19:24 UTC, steppefox commented on index.html
> +                                <img src="img/main-entry.jpg" title="Спасение туриста на перевале
У картинок желательно заполнять `alt`, можно продублировать из `title`. Исходное изображение больше необходимого на выводе в пару раз.

2016-11-08 19:24 UTC, steppefox commented on index.html
> +                        <img src="img/opera-2.jpg" title="Конференция Opera Software" alt=""
Тоже самое

2016-11-08 19:24 UTC, steppefox commented on index.html
> +                        <img src="img/opera-1.jpg" title="Конференция Opera Software" alt=""
Тоже самое

2016-11-08 19:24 UTC, steppefox commented on index.html
> +        <p>№23 (1052) 31 октября 2016г. | <a href="http://ngzt.ru">www.ngzt.ru</a>,
Дата должна быть обернута в тег даты

2016-11-08 19:24 UTC, steppefox commented on index.html
> +            <a href="http://vk.com/ngztekb" target="_blank">vk.com/ngztekb</a></p>
Ссылки на соцсети и внешние ресурсы должны содержать `rel="nofollow"`

2016-11-08 20:32 UTC, Alex768 commented on index.css
> +    height: auto !important;
Это верно только если колонки фиксированные по ширине, но если свёрстано резиново (как в моём случае), а количество колонок фиксировано, то изображения будут либо меньше отведённого размера, либо выползут за пределы своей колонки.

2016-11-08 20:32 UTC, Alex768 commented on index.css
> +    overflow: hidden;
float'ом 2 блока с цитатой и погодой размещал по краям)) забыл убрать после того, как сделал таблицей header

2016-11-08 20:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 20:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 21:01 UTC, Alex768 commented on index.css
> +    src: url('fonts/GothicRus.woff') format('woff'), url('fonts/GothicRus.ttf') format('truetype');
С текущей конфигурацией линтера это не получается: с одной стороны
Expected single space after ","    value-list-comma-space-after и это когда 8 пробелов после переноса строки после "," хотя в столбик выводил при первом коммите. Текущий вариант с несколькими src корректен?

2016-11-08 21:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-08 21:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-09 07:27 UTC, steppefox commented on index.css
> +    src: url('fonts/GothicRus.woff') format('woff'), url('fonts/GothicRus.ttf') format('truetype');
С текущей конфигурацией линтера можно делать вот так:

```
src: url('fonts/GothicRus.woff') format('woff')
     , url('fonts/GothicRus.ttf') format('truetype');
```

Немного некрасиво, но лучше чем в строку

2016-11-09 09:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-10 11:20 UTC, steppefox commented
👍

2016-11-10 11:20 UTC, steppefox approved these changes

2016-11-10 11:21 UTC, closed without merging

2016-12-14 12:13 UTC, mokhov commented
Звездочку показал на апелляции