Борзов Артем
urfu-2016/markup-task-4 pull request #56
Opened 2016-10-31 17:41 UTC by Qoter

2016-10-31 17:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 18:06 UTC, bazhenova commented
Самое первое, что бросается в глаза - ужасно сделаны переносы. Так лучше никогда не делать. Надо обязательно поправить

2016-11-01 18:13 UTC, bazhenova commented
Теперь по поводу требований. Некоторые не реализованы:
```
1) Есть, конечно, картинки и подписи к ним, иногда они занимают несколько! колонок
2) В тексте используются переносы (давай сделаем нормальные)
3) Изредка текст пишут:
В
О
Т

Т
А
К
```

2016-11-01 18:17 UTC, bazhenova commented
Поехала верстка при разрешении 1280х960
![image](https://cloud.githubusercontent.com/assets/12410663/19901558/408ca454-a089-11e6-8909-147bfe576a99.png)

2016-11-01 18:19 UTC, bazhenova commented on index.html
> +
Зачем пустые строчки между тегами? Поправь во всем файле

2016-11-01 18:20 UTC, bazhenova commented on index.html
> +        <img src="img.jpg" alt="lemur">
Добавь атрибут `title` к картинкам

2016-11-01 18:23 UTC, bazhenova commented on index.css
> +    src: url(fonts/Overpass.ttf);
Как минимум добавь еще woff формат. Будет вообще круто, если добавишь еще и eot)

2016-11-01 18:27 UTC, bazhenova commented on index.css
> +    border-top: 1px solid black;
Кажется, тут можно обойтись без дублирования кода. Посмотри в сторону `border`, а определенные правила можно задать дополнительно.

2016-11-01 18:27 UTC, bazhenova commented on index.css
> +    column-rule: 1px solid darkslategray;
Цвета лучше указывать в hex формате. Поправь во всем файле, это не единственное место

2016-11-01 18:32 UTC, bazhenova commented on index.css
> +.column > p:first-of-type::first-letter
Вместо описывания свойств для определенных тегов, лучше использовать классы. Например, какой-то из первых параграфов ты захочешь оформить по-другому. Тогда можно будет просто навесить на него класс вместо переписывания стилей. Посмотри еще по коду, у тебя есть еще несколько мест, где лучше использовать классы

2016-11-01 18:34 UTC, bazhenova commented on index.css
> +    margin-bottom: 10px;
Давай будем оптимально записывать свойста. Почитай еще раз про `margin`. Тогда не придется отдельно прописывать свойства `margin-top` и `margin-bottom`

2016-11-01 18:36 UTC, bazhenova commented on index.css
> +    font-size: 200%;
Тут тоже бы оптимизировать. Я про `font-size` и `font-family`. Давай вспомним про `font`.

2016-11-01 18:37 UTC, bazhenova commented
🍅

2016-11-06 16:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 17:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 18:56 UTC, bazhenova commented
![image](https://cloud.githubusercontent.com/assets/12410663/20040627/8d7ba5a2-a47c-11e6-873c-efc774413069.png)
Выглядит не очень в Firefox

2016-11-06 19:00 UTC, bazhenova commented on index.css
> +    src: url(fonts/Edisson.ttf), url(fonts/Edisson.woff), url(fonts/Edisson.eot);
Укажи еще `format` для каждого

2016-11-06 19:00 UTC, bazhenova commented on index.css
> +    src: url(fonts/Five.ttf), url(fonts/Five.woff), url(fonts/Five.eot);
`format`

2016-11-06 19:00 UTC, bazhenova commented on index.css
> +    font-size: 120%;
`font-*` -> `font`

2016-11-06 19:03 UTC, bazhenova commented on index.css
> +article.two-columns
Можно просто указывать классы без тегов:
```
.two-columns
{
    ...
}
```

2016-11-06 19:04 UTC, bazhenova commented on index.css
> +article.two-columns
И не только в этом месте

2016-11-06 19:05 UTC, bazhenova commented on index.html
> +
Пустые строки все еще здесь)

2016-11-06 19:09 UTC, bazhenova commented on index.css
> +    columns: 2;
Безвендорное правило лучше указывать после правил с вендорными префиксами, даже если оно никем не поддерживается

2016-11-06 19:11 UTC, bazhenova commented on index.css
> +article
Давай вместо тегов лучше будем использовать классы, так как может понадобиться оформить их по-разному. Посмотри во всем файле

2016-11-06 19:12 UTC, bazhenova commented
Доп. задание будешь делать?

2016-11-06 19:12 UTC, bazhenova commented
🍅

2016-11-06 19:32 UTC, bazhenova commented on index.css
> +    height: auto;
Тут точно нужно это правило?

2016-11-06 20:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 20:13 UTC, Qoter commented on index.css
> +    height: auto;
Ну да, иначе картинка будет в полный размер, а так по размеру колонки.

2016-11-07 05:07 UTC, bazhenova commented on index.css
> +    height: auto;
Я имею в виду, что если убрать это правило, то ничего не меняется, у тебя ширина задана
![image](https://cloud.githubusercontent.com/assets/12410663/20047021/e7ca2e52-a4d1-11e6-9062-4e5dbe32bcc8.png)

2016-11-07 05:20 UTC, bazhenova commented
Еще разок напомню, что можно в css писать просто классы без указания тегов + `height: auto` можно не указывать. А так норм, передаю ментору.

2016-11-07 05:20 UTC, bazhenova commented
🚀

2016-11-07 10:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 19:27 UTC, mokhov commented on index.css
> +    font: 400 250% Edisson;
а где здесь деградация до дефолтного шрифта?

2016-11-07 19:27 UTC, mokhov commented on index.css
> +    font: normal 200% Edisson;
normal будет по-умолчанию

2016-11-07 19:28 UTC, mokhov commented on index.css
> +    float: left;
float запрещен

2016-11-07 19:30 UTC, mokhov requested changes

2016-11-07 19:30 UTC, mokhov commented on index.css
> +    src: url(fonts/Edisson.ttf) format('truetype'), url(fonts/Edisson.woff) format('woff'), url(fonts/Edisson.eot) format('embedded-opentype');
не хватает local

2016-11-07 19:30 UTC, mokhov commented on index.html
> +    <span class="header-text">Газета узбагозета</span>
зачем нужен отдельный элемент?

2016-11-07 19:30 UTC, mokhov commented on index.html
> +        <p class="first">Пу&shy;тин про&shy;ком&shy;мен&shy;ти&shy;ро&shy;вал фра&shy;зу
есть селектор для выбора первого параграфа

2016-11-07 19:30 UTC, mokhov commented
🍅

2016-11-07 19:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 20:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 19:43 UTC, Qoter commented
🍏

2016-11-10 16:06 UTC, closed without merging