Брагин Егор
urfu-2016/markup-task-4 pull request #6
Opened 2016-10-27 23:09 UTC by eoL95

2016-10-27 23:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-28 18:49 UTC, FrodoTheTrue commented
![2016-10-28 23 47 51](https://cloud.githubusercontent.com/assets/9107905/19818419/246253dc-9d69-11e6-93ff-726351e1fdb7.png)

2016-10-28 18:52 UTC, FrodoTheTrue commented
![2016-10-28 23 48 07](https://cloud.githubusercontent.com/assets/9107905/19818443/42104fec-9d69-11e6-9575-05e53a23e8fa.png)
Шрифт не применился

2016-10-28 18:53 UTC, FrodoTheTrue commented
А вообще круто сверстано 👍

2016-10-28 20:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-29 06:50 UTC, FrodoTheTrue commented on index.html
> +                <img src="img/woman.jpg" alt="woman">
нужно добавить атрибут title

2016-10-29 06:56 UTC, FrodoTheTrue commented on index.css
> +    src: url(fonts/OldNewspaperTypes.ttf);
будет круто, если используешь тут woff и eot

2016-10-29 07:03 UTC, FrodoTheTrue commented
а где же вот такой текст? 😞 :
```
В
О
Т

Т
А
К
```

2016-10-29 07:13 UTC, FrodoTheTrue commented on index.css
> +    background: lightblue;
лучше использовать #ADD8E6

2016-10-29 07:13 UTC, FrodoTheTrue commented
:tomato:

2016-10-30 11:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-30 11:08 UTC, eoL95 commented on index.css
> +    src: url(fonts/OldNewspaperTypes.ttf);
eot в лекции сказано можно не использовать, woff и атрибут local добавил

2016-10-30 11:08 UTC, eoL95 commented
🍏

2016-10-30 11:10 UTC, eoL95 commented on index.css
> +    src: url(fonts/OldNewspaperTypes.ttf);
И там пришлось запятые с новой строчки ставить, а то линтер ругался непонятно почему :D

2016-10-30 11:40 UTC, FrodoTheTrue commented
🚀

2016-10-31 08:39 UTC, FrodoTheTrue commented
🚀

2016-11-06 06:53 UTC, steppefox requested changes
🍅

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 70px;
Кажется это не подпадает под изменяемый размер шрифта. Конечно заголовок статьи большой и его прекрасно видно, но в некоторых случаях он может быть слишком гигантским и разумно иметь возможность его уменьшать (например если ты верстаешь еще и мобильную версию, то заголовок в 70px это беда).

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 30px;
Аналогично

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 30px;
Аналогично

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    margin-top: 5%;
Вертикальные `margin` очень редко бывают в процентах

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    left: 10px;
Тут у тебя проблема, что логически `copyright-header` должен выравниваться относительно блока `header`, а на практике оно выравнивается относительно края экрана

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    height: 120px;
А зачем здесь такая фиксация по высоте?

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 12px;
Размер шрифта в px =(

2016-11-06 06:53 UTC, steppefox commented on index.html
> +                <span>EKATERINBURG, THURSDAY, OCTOBER 27, 1985</span>
Дата должна быть в теге описывающем дату

2016-11-06 06:53 UTC, steppefox commented on index.html
> +                <span>EKATERINBURG, THURSDAY, OCTOBER 27, 1985</span>
Если тебе визуально нужно вывести текст большими буквами, в CSS есть специальное свойство для этого

2016-11-06 06:53 UTC, steppefox commented on index.html
> +                <h4>LATE CITY EDITION</h4>
Если тебе визуально нужно вывести текст большими буквами, в CSS есть специальное свойство для этого

2016-11-06 06:53 UTC, steppefox commented on index.html
> +    <input type="checkbox" class="change-color">Сменить цветовую схему
Было бы здорово иметь возможность переключать radio и чекбоксы тыкая по надписям

2016-11-06 06:53 UTC, steppefox commented on index.html
> +                <img src="img/woman.jpg" alt="woman" title="woman">
К сожалению это не очень хорошее описание содержимого картинки, к изображениям нужно прикладывать более развернутое содержимое

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 20px;
Размер шрифта в px =(

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font: 12px 'Times New Roman';
Размер шрифта в px =(

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 20px;
Размер шрифта в px =(

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    margin-right: 40px;
Чем обусловлен такой отступ? Из-за этого третья колонка немного отъехала в сторону

2016-11-06 06:53 UTC, steppefox commented on index.css
> +    font-size: 40px;
Размер шрифта в px =( Из-за этого при смене размера шрифта первая буква всегда одного размера

2016-11-06 06:53 UTC, steppefox commented on index.html
> +                    <h3>Meeting her idol</h3>
При выборе маленького размера шрифта, заголовок статьи остается в конце первого столбца, а содержимое уезжает на второй =( Визуально - это не правильно

2016-11-06 10:24 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 10:26 UTC, eoL95 commented on index.css
> +    height: 120px;
Чтобы высота была такая же как у `header`

2016-11-06 10:27 UTC, eoL95 commented on index.css
> +    margin-right: 40px;
Без отступа выглядит не очень, оставил 10px

2016-11-06 15:43 UTC, steppefox requested changes
🍅

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    font-size: 5em;
Проблема в том, что при смене размера шрифта, у тебя заголовок не меняется размером и не только он =(

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    height: 120px;
с absolute'ным элементом все было нормально, и опять таки, зачем height: 120px? А еще в этом задании не хорошо использовать `float` элементы

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    column-rule: 1px solid black;
У колонок границы каждый раз оканчиваются по разному по высоте, где-то они доходят до края газеты, где-то на середине обрываются. Смотрится не аккуратно.

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    text-transform: uppercase;
Пожалуйста, не используй глобальные селекторы вроде span, дай элементам осмысленные классы и примени стили

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    overflow: hidden;
Когда уберешь у `copyright-header` float, можно будет убрать overflow

2016-11-06 15:43 UTC, steppefox commented on index.css
> +    overflow: hidden;
Вот это зачем глобально у всех div?

2016-11-06 17:46 UTC, eoL95 commented on index.css
> +    column-rule: 1px solid black;
А как их продолжить до одного уровня? Есть вариант просто убрать их тогда

2016-11-06 17:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 17:50 UTC, eoL95 commented
🍏

2016-11-06 18:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 18:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:45 UTC, steppefox requested changes
🍅

2016-11-06 19:45 UTC, steppefox commented on index.css
> +    overflow: hidden;
Зачем здесь `overflow:hidden`?

2016-11-06 19:45 UTC, steppefox commented on index.css
> +    column-count: 2;
Неправильный порядок свойств. Сначала должны идти вендорные свойста:
`-moz-`, `-webkit-` и тд, а потом безвендорные. Тоесть:

```
-moz-column-count: 2;
-webkit-column-count: 2;
column-count: 2;

-moz-column-rule: 1px solid;
-webkit-column-rule: 1px solid;
column-rule: 1px solid;
```

Поправить соответственно везде

2016-11-06 19:45 UTC, steppefox commented on index.html
> +                <img src="img/woman.jpg" alt="Annie Edson Taylor" title="Annie Edson Taylor">
Я продолбал замечание =( У картинок нужно указывать аттрибуты width и height, это влияет на скорость рендеринга изображений в браузерах

2016-11-06 19:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 05:36 UTC, steppefox commented
Теперь вроде норм) 

Работа в целом хорошая, газета сделана под старину. 

Есть мелкие замечание по поводу контента - "рыба" для заданий по хорошему всегда должна соответствовать работе. В данной работе - газета сделана под старину, но часть новостей современные. Так же, есть диссонанс в названии газеты и его содержимым. Соответствующий контент в работе - улучшает восприятие. Никогда не стоит использоваться "пустые" рыбы или LoremIpsum.

В остальном вроде все норм, поэтому PR закрываю.

2016-11-07 05:36 UTC, closed without merging