Макаров Виталий
urfu-2016/markup-task-4 pull request #65
Opened 2016-10-31 19:00 UTC by FairTex

2016-11-02 06:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-02 17:05 UTC, Mokoshka commented
Куда-то фон делся(
![image](https://cloud.githubusercontent.com/assets/14892550/19938863/497a3f62-a148-11e6-8440-fcfb83360a3c.png)
И допы не заработали, обидно(
![image](https://cloud.githubusercontent.com/assets/14892550/19938894/6efc492e-a148-11e6-98d5-42c0d7523069.png)

2016-11-02 17:07 UTC, Mokoshka commented on index.css
> +img
Лучше навесить на класс. А то вдруг твоя душа потребует логотип для газеты, а он будет такой большой

2016-11-02 17:08 UTC, Mokoshka commented on index.css
> +}
Селекторы с одинаковым набором правил можно объединить, перечислив их через запятую

2016-11-02 17:22 UTC, Mokoshka commented on index.html
> +                <p>Friends say the red-haired royal Romeo, often dubbed the world’s most eligible bachelor,
Давай везде, где текст в параграфе не влазит в одну строку, поправим
```
<p>
    Много текста
</p>
```

2016-11-02 17:26 UTC, Mokoshka commented on index.css
> +    text-align: center;
text-align наследуемое свойство. Можно внести это правило в селектор .data

2016-11-02 17:30 UTC, Mokoshka commented on index.html
> +    <p><input type="radio" name="size" class="small-size">Small</p>
У input есть замечательный парный тэг label, Попробуй воспользоваться им

2016-11-02 17:31 UTC, Mokoshka commented
🍅

2016-11-05 15:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 09:37 UTC, Mokoshka commented
Давай в firefox добавим колонки, а то они куда-то пропали
![image](https://cloud.githubusercontent.com/assets/14892550/20036271/0accd97e-a426-11e6-9e46-66c42dd97d90.png)

2016-11-06 09:38 UTC, Mokoshka commented on index.css
> +    background-color: black;
Цвета лучше задавать hex-кодом. Поправь для всех цветов в коде

2016-11-06 09:39 UTC, Mokoshka commented on index.css
> +    /*font-family: 'Viga', sans-serif;*/
⚠️

2016-11-06 09:41 UTC, Mokoshka commented on index.html
> +                <p>Friends say the red-haired royal Romeo, often dubbed the world’s most eligible bachelor,
🆙

2016-11-06 09:42 UTC, Mokoshka commented on index.html
> +        <div class="left">
Может лучше здесь использовать section вместо div. Будет лучше ведь

2016-11-06 09:44 UTC, Mokoshka commented
Выглядит неплохо, хочется увидеть исправления замечаний

2016-11-06 09:44 UTC, Mokoshka commented
🍅

2016-11-06 10:15 UTC, FairTex commented on index.html
> +        <div class="left">
Секшен требует заголовок после него, поэтому я решил отказаться в пользу дива

2016-11-06 10:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 11:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 15:21 UTC, Mokoshka commented on index.html
> +        <div class="left">
Это линтинг так просит?

2016-11-06 15:24 UTC, Mokoshka commented on index.css
> +    column-count: 3;
Беспрефиксное правило должно находиться после правил с вендорными префиксами

2016-11-06 15:25 UTC, Mokoshka commented on index.html
> +                <img src="images/cold.jpg" alt="Cold" class="weather-img">
Добавь еще атрибут title для картинки

2016-11-06 15:25 UTC, Mokoshka commented on index.html
> +                    this week.</h5>
Так задумано?)

2016-11-06 15:26 UTC, Mokoshka commented
Не надо игнорировать мою просьбу добавить отступ для параграфов( И расставь мягкие переносы в текстах.
Поправишь замечания и передам задачу ментору

2016-11-06 15:26 UTC, Mokoshka commented
🍅

2016-11-06 17:41 UTC, FairTex commented on index.html
> +        <div class="left">
Да

2016-11-06 18:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 18:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 18:13 UTC, Mokoshka commented
Чтобы не мучать Хрюнделя и не придумывать постоянно названия коммитам, можно запускать линтинг локально)

2016-11-06 18:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 18:40 UTC, Mokoshka commented on index.html
> +                    Rachel Zane in American TV legal drama Suits.<br>
Ну нет, только не br.
Надо было то всего лишь поставить два переноса строк: после <p> и перед </p>. И изменить длину строк, чтобы линтер не ругался

2016-11-06 18:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 18:49 UTC, Mokoshka commented on index.html
> +                <p>Friends say the red&shy;haired ro&shy;y&shy;al Ro&shy;me&shy;o, of&shy;ten dubbed
Здесь бы тоже перенос строки после `<p>`. И верни разбиение текста на параграфы

2016-11-06 18:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 18:56 UTC, Mokoshka commented on index.html
> +                    <br>
Ну почему br? Чем тебе не нравится тег <p>?

2016-11-06 18:57 UTC, Mokoshka commented on index.html
> +                    <br>
```
<p>
   Текст
</p>
<p>
   Текст
</p>
```

2016-11-06 18:58 UTC, FairTex commented on index.html
> +                    <br>
Неправильно понял предыдущее замечание(

2016-11-06 19:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:01 UTC, Mokoshka commented on index.html
> +                    <br>
⚠️ 
Повнимательнее

2016-11-06 19:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:07 UTC, Mokoshka commented
🚀

2016-11-07 07:52 UTC, steppefox requested changes
🍅

2016-11-07 07:52 UTC, steppefox commented on index.css
> +@import url('https://fonts.googleapis.com/css?family=Special+Elite|Diplomata+SC|Viga|Indie+Flower|Nova+Mono');
Шрифты очень классные, хорошо подобрал. Однако попробуй подключить хотя-бы один шрифт локально руками (тоесть что-бы файлы шрифтов лежали у тебя в проекте и ты подключал их). Цель: что-бы ты действительно на практике знал какие-шрифты нужно подключать и как.

2016-11-07 07:52 UTC, steppefox commented on index.css
> +    overflow: hidden;
А зачем он здесь?

2016-11-07 07:52 UTC, steppefox commented on index.css
> +    width: 100%;
Зачем здесь width:100% если header уже display:block?

2016-11-07 07:52 UTC, steppefox commented on index.css
> +    font-size: 40px;
Изменение размера шрифта должно применяться и к заголовку.

2016-11-07 07:52 UTC, steppefox commented on index.html
> +            <td>WIND</td>
Если нужно вывести текст большими буквами, всегда лучше применить специальное CSS свойство для этого

2016-11-07 07:52 UTC, steppefox commented on index.html
> +            <p>SUNDAY, OCTOBER 30, 2016</p>
Если есть дата, то нужно оборачивать её в специальный тэг даты

2016-11-07 07:52 UTC, steppefox commented on index.html
> +                <img src="images/cold.jpg" alt="Cold" class="weather-img" title="Cold">
Слишком короткое описание содержимого картинки в alt и title. Cold может расцениваться как погода или простуда или еще что-нибудь =/ Так же в картинке необходимо указать аттрибуты width, height. Исходная картинка по размеру больше чем необходимо для вывода. К тому же она едет в FireFox.

2016-11-07 07:52 UTC, steppefox commented on index.html
> +            <p>ONE PENNY</p>
Визуально надписи поехали по вертикали =( Должны быть все три на одном уровне.

2016-11-07 18:37 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 18:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 19:08 UTC, steppefox requested changes
🍅

2016-11-07 19:08 UTC, steppefox commented on index.css
> +    src: url(SpecialElite.ttf) format(truetype);
Желательно, дополнительно подключить woff и woff2

2016-11-07 19:08 UTC, steppefox commented on index.css
> +    font-size: 30px;
Желательно, что-бы базовый шрифт изменялся сразу для всех блоков (header, main), одним применением стиля. Имеет смысл обернуть header, main общим родителем и применять изменение размера шрифта к нему, а что-бы у header'а и остальных элементов  размер менялся сам соответственно

2016-11-07 19:08 UTC, steppefox commented on index.css
> +    font-size: 40px;
Повторюсь, здесь должны быть em

2016-11-07 19:08 UTC, steppefox commented on index.html
> +            <td>WIND</td>
Повторюсь, буквы большими нужно делать средствами CSS, в тексте они должны быть нормального формата

2016-11-07 19:08 UTC, steppefox commented on index.html
> +                    alt="The weather will be cool" class="weather-img"
Зачастую, `title` и `alt` должны совпадать по содержимому. К тому же, `the weather will be cool` является неверным содержимым иллюстрации судя по тексту статьи. Исходное изображение по прежнему больше чем необходимо.

2016-11-07 19:08 UTC, steppefox commented on index.html
> +                    Trick&shy;or&shy;treaters will en&shy;joy a ver&shy;y mild Hal&shy;low&shy;een with
Блок выглядит не аккуратно и должен быть по уровню изображения (или изображение должно быть по уровню параграфов).

![image](https://cloud.githubusercontent.com/assets/4667275/20071582/d2abc510-a546-11e6-85ac-f8baa38e018e.png)

2016-11-07 19:08 UTC, steppefox commented on index.html
> +                <h5>Other news</h5>
Блок выглядит не аккуратно, текст слишком прижат к краям. Так же визуально блок выглядит как цитата, но для цитат есть другой тег.

![image](https://cloud.githubusercontent.com/assets/4667275/20071664/2bf4149c-a547-11e6-8844-aeb6dd2ee2f8.png)

2016-11-07 19:08 UTC, steppefox commented on index.css
> +td
Пожалуйста, не используй глобальные правила вроде `td`, у таблицы есть класс, почему бы не использовать его в селекторе?

2016-12-03 11:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 07:32 UTC, steppefox commented
В целом норм, осталось сделать два пункта:

* Повторяю в 3й раз: ИСХОДНОЕ изображение с зонтиком нужно уменьшить физически (в фотошопе / растровом редакторе). Потому что нет необходимости на странице в картинке бОльшего размера чем 300px (и это у меня дисплей 1920px,  в ширину, на нормальных экранах необходимый размер на самом деле еще меньше). Почему нужно уменьшать картинки до размеров максимально подходящих под реально выводимые? Потому что меньше вес и проще рендерить браузеру. Да с адаптивными это все надо еще проверять и считать, но картинка в 500px тут точно не нужна.

* Не выполнен пункт с вертикальным текстом. На странице обязательно должен быть один вертикальный блок.

2016-12-07 07:32 UTC, steppefox requested changes
🍅

2016-12-07 12:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 12:20 UTC, FairTex commented
@steppefox

2016-12-07 14:02 UTC, steppefox requested changes
🍅

2016-12-07 14:02 UTC, steppefox commented on index.html
> +                    Vertical text align
Отлично. Только такой текст будет странно смотреться в газете, не считаешь?

2016-12-07 14:02 UTC, steppefox commented on index.css
> +    float: left;
В задании запрещено использовать плавающие элементы

2016-12-07 14:02 UTC, steppefox commented on index.css
> +    width: 15px;
Ширина чуть больше чем текст, от этого визуально смотрится не аккуратно. Либо нужно выравнивать текст по центру, либо делать ширину меньше.

2016-12-07 14:02 UTC, steppefox commented on index.css
> +    width: 15px;
![image](https://cloud.githubusercontent.com/assets/4667275/20970464/94d278bc-bcaf-11e6-8119-16fc211a7d30.png)

В целом блок выглядит не аккуратно. Дальше идущий текст слишком прижимается к вертикальному блоку.

2016-12-07 14:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-08 05:19 UTC, steppefox commented
В Night Mode - текст в вертикальном блоке становится не читаем. 

![image](https://cloud.githubusercontent.com/assets/4667275/20998416/80f0fd16-bd2f-11e6-8e0c-46e9775349fe.png)

Ну и блок почему-то за границами основной газеты =/ А должен быть внутри, как было примерно в первом варианте с вертикальным блоком

2016-12-08 05:20 UTC, steppefox commented
🍅

2016-12-09 12:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-09 13:03 UTC, steppefox approved these changes

2016-12-09 13:04 UTC, closed without merging