Быстрова Виктория
urfu-2016/markup-task-4 pull request #67
Opened 2016-10-31 20:01 UTC by bvvvvb

2016-10-31 20:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 20:04 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-31 20:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-01 10:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-03 14:08 UTC, mironov-alexey commented
![image](https://cloud.githubusercontent.com/assets/6783167/19969038/d9bf7dac-a1f8-11e6-82dd-bd758d86fcbd.png)
Firefox

2016-11-03 14:08 UTC, mironov-alexey commented
![image](https://cloud.githubusercontent.com/assets/6783167/19969054/e8c704fa-a1f8-11e6-8268-20f4f82e955b.png)
Chrome

2016-11-03 14:12 UTC, mironov-alexey commented
А ещё как-то не заметил вертикального текста:
```
Изредка текст пишут:
В
О
Т

Т
А
К
```

2016-11-03 14:12 UTC, m1ralx commented
И подписей к картинкам нет(

2016-11-03 14:13 UTC, mironov-alexey commented on index.html
> +                        alt="Енот моет погоду в тазике"
ещё title надо к картинкам, и указать для них width и height

2016-11-03 14:13 UTC, mironov-alexey commented
🍅

2016-11-03 14:17 UTC, bvvvvb commented on index.html
> +                        alt="Енот моет погоду в тазике"
"Вам нужно сверстать эту электронную газету так, чтобы она выглядела максимально похоже на газету из 85 год. Вот некоторые особенности газетной вёрстки того времени". Может я что-то не так понимаю, но для меня максимально похоже не равно сделайте с использованием абсолютно всех свойств. Подписи к картинкам - ок, но 
в
о
т
э
т
о
п
р
о
с
т
о
и
з
у
р
о
д
у
е
т
р
а
б
о
т
у

2016-11-03 14:25 UTC, mironov-alexey commented on index.html
> +                        alt="Енот моет погоду в тазике"
@bvvvvb это требования к задаче. Можно сделать так, чтобы не изуродовало и смотрелось приемлемо

2016-11-05 03:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-05 03:08 UTC, bvvvvb commented
🍏

2016-11-05 06:51 UTC, bvvvvb commented on index.html
> +                        alt="Енот моет погоду в тазике"
width для картинок я задала в css

2016-11-06 06:38 UTC, mironov-alexey commented on index.css
> +    background: url(images/background.jpg);
Нужно указывать шрифт, который будет использоваться по-умолчанию

2016-11-06 06:40 UTC, mironov-alexey commented on index.html
> +    <table class="content">
table в этой задаче можно использовать только для таблиц. Это что-то совсем не таблица по смыслу

2016-11-06 06:41 UTC, m1ralx requested changes
Надо переделать без таблицы

2016-11-06 06:41 UTC, mironov-alexey commented
🍅

2016-11-06 19:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 19:06 UTC, bvvvvb commented
🍏

2016-11-06 19:09 UTC, bvvvvb commented
Я хотела, чтобы основной текст занимал больше места по сравнению с другими, а теперь вот 50 на 50 без table 😞

2016-11-07 09:08 UTC, mironov-alexey commented
🚀

2016-11-07 15:39 UTC, msmirnov reviewed
Хотелось бы ограничить ширину, потому что на узком экране выглядит не очень
![image](https://cloud.githubusercontent.com/assets/2646531/20063736/1ed0e172-a52a-11e6-942e-1121c24e4004.png)

2016-11-07 15:39 UTC, msmirnov commented on index.css
> +.weather div
Лучше на эти дивы навешать класс и писать стили для него. Так, конечно, тоже можно, но это 1) Менее производительно 2) Может взорваться, когда захочешь внутрь `div` положить ещё какой-нибудь `div`

2016-11-07 15:39 UTC, msmirnov commented
Точно не будешь делать доп задание?

2016-11-07 15:39 UTC, msmirnov commented
🍅

2016-11-07 18:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-07 19:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 19:03 UTC, bvvvvb commented
🍏

2016-11-07 19:03 UTC, bvvvvb commented
Сделала доп задание ))

2016-11-08 04:25 UTC, closed without merging