Бабушкина Анастасия
urfu-2016/markup-task-4 pull request #9
Opened 2016-10-28 20:28 UTC by AnastasiaBabushkina

2016-10-28 20:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 20:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 21:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 21:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 21:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 21:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 21:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 22:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 22:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-28 22:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-10-30 19:01 UTC, Dotokoto commented
Привет! Замечания по внешнему виду (первый скрин - chrome, второй - firefox):
1) Подзаголовок газеты при ширине экрана 1440px находится не посередине строки
2) Некрасиво вылезает элемент с надписью "Всё самое интересное" 
3) В chome не все шрифты устанавливаются (например, в заголовке)
4) В firefox при ширине экрана 1440px картинка с котиками в космосе прилипает к верху газеты, красивее выглядело бы с отступом
![2016-10-30 23-49-53](https://cloud.githubusercontent.com/assets/8973726/19838980/51fe13de-9f04-11e6-8aa4-a03808918898.png)
![2016-10-30 23-50-12](https://cloud.githubusercontent.com/assets/8973726/19838984/67659152-9f04-11e6-9701-cab221c290aa.png)

2016-10-30 19:13 UTC, Dotokoto commented
5) В firefox колонки не разбиваются на подколонки
6) В этом шрифте цифры очень маленького размера, их почти не видно :(
И еще, не хватает некоторых моментов из описания задачи: выделения первых букв параграфов, вертикального текста. 
![2016-10-31 00-07-02](https://cloud.githubusercontent.com/assets/8973726/19839109/8a7f4460-9f06-11e6-9f29-323c873925fc.png)
![2016-10-31 00-07-25](https://cloud.githubusercontent.com/assets/8973726/19839110/8ebd6aca-9f06-11e6-8b12-9a722c0a55b8.png)

2016-10-31 09:18 UTC, Dotokoto commented on index.html
> +            ЕКАТЕРИНБУРГ, ВОСКРЕСЕНЬЕ 30 ОКТЯБРЯ, 2016
Можно завернуть дату в тег ```<time></time>```

2016-10-31 09:18 UTC, Dotokoto commented on index.html
> +    <div class="under-header">
Это тоже часть header

2016-10-31 09:19 UTC, Dotokoto commented on index.html
> +        <div class="date">
Это похоже на подзаголовок, можно использовать тег h2

2016-10-31 09:21 UTC, Dotokoto commented on index.html
> +        <h2 class="interesting">
Плохое название класса, оно привязано к тексту внутри. А по логике это подзаголовок или название статьи

2016-10-31 09:24 UTC, Dotokoto commented
У тебя много лишних пустых строк в html. По [кодстайлу](https://github.com/urfu-2016/guides/blob/master/codestyle/html.md) лишние строки оставлять не нужно. Убери их везде, где есть

2016-10-31 09:27 UTC, Dotokoto commented on index.html
> +    <article>
Всё после header стоит еще дополнительно завернуть в main - потому что там находится основной контент страницы

2016-10-31 09:29 UTC, Dotokoto commented on index.html
> +    <article>
И можно выделить несколько article. Кажется, что у тебя не одна цельная статья. А как минимум две - кто лучше и про космос

2016-10-31 09:31 UTC, Dotokoto commented on index.html
> +        class="kosmonavt"
Тоже плохое название класса. Отличие от других картинок в том, что у этой закругленные углы

2016-10-31 09:35 UTC, Dotokoto commented on index.css
> +    -moz-column-rule: 2px solid #000;
Свойства с префиксами всегда пишутся в css до свойств без префиксов. Так как применяется последнее найденное свойство. А префиксы обычно указывают на недоделанную или не соответствующую спецификации реализацию. После доработки переходят на названия без префиксов.
Соответственно, при применении свойства с префиксом могут вылезти всякие баги. Которых без префикса не будет

2016-10-31 09:35 UTC, Dotokoto commented on index.css
> +.autor
author

2016-10-31 09:47 UTC, Dotokoto commented
:tomato: Посмотрела, есть замечания по содержанию газеты и по верстке. Дополни содержимое в соответствии с текстом задания (я выше написала, чего не хватает). Еще было бы круто подключить какой-нибудь шрифт не из GoogleFonts, а с помощью @font-face.
Жду исправлений, если будут вопросы - пиши. После того, как будешь готова написать, оставь здесь комментарий с эмодзи зеленого яблочка (как в тестах). И можешь дополнительно написать мне в Slack (@dotokoto), чтобы я быстрее увидела

2016-11-04 20:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 21:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 21:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 21:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-04 21:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-04 21:31 UTC, AnastasiaBabushkina commented
🍏 исправила замечания

2016-11-06 07:25 UTC, Dotokoto commented on index.css
> +@font-face
Лучше вынеси объявление шрифта в начало файла, чтобы отделять его от самих стилей

2016-11-06 07:29 UTC, Dotokoto commented on index.css
> +    src: url(CormorantInfant-Bold.ttf);
Надо еще указать атрибут local. И ttf - устаревший для web формат шрифта + он много весит. Лучше подключать шрифты с форматами woff, woff2. И можно в подключении указать тип шрифта:
``` src: url(CormorantInfant-Bold.ttf) format('truetype'),
           url(CormorantInfant-Bold.woff) format('woff')

2016-11-06 07:29 UTC, Dotokoto commented on index.css
> +P:first-letter
Почему p с большой буквы?

2016-11-06 07:30 UTC, Dotokoto commented on index.css
> +html
html лучше тоже вынести поближе к началу файла

2016-11-06 07:34 UTC, Dotokoto commented on index.html
> +            ЕКАТЕРИНБУРГ, <time>2016-11-05</time>
Почему эта часть в main? Даже по названию класса видно, что должна быть скорее в header (и по верстке тоже, кажется что header отделен черными полосами от основного содержания)

2016-11-06 07:35 UTC, Dotokoto commented on index.html
> +            <img src="http://popugai-market.ru/images/8/8749.jpg" alt="кошка или собака">
Картинкам стоит еще прописать атрибуты height и width. Тогда браузер будет сразу выделять место под эту картинку, и страница не будет "скакать" после того, как картинка загрузилась и заняла место

2016-11-06 07:37 UTC, Dotokoto commented on index.html
> +    <aside class="vertical_right">К О Ш К И</aside>
Для этих элементов вместо float можно использовать ```position: absolute; left: 0 (или right: 0)```. Будет то же самое. Но от float можно огрести больше побочных эффектов

2016-11-06 07:39 UTC, Dotokoto commented on index.css
> +article.one
Можно назвать класс article-one и использовать только селектор по классу, без тега

2016-11-06 07:41 UTC, dotokoto commented on index.css
> +    font-size: 200%;
font-size и font-family можно объединить в один атрибут font (то же самое сделай в правилах ниже)

2016-11-06 07:43 UTC, Dotokoto commented
Все еще не нравится, как надписать "Всё самое интересное" вылезает. Давай ее либо на всю строку и посередине. Либо заканчивать ровно в конце первой колонки. А то она растянута на полторы колонки, некрасиво (
![- mozilla firefox 2016-11-06 12 23 51](https://cloud.githubusercontent.com/assets/8973726/20036085/77e4413a-a41e-11e6-9ec9-997332fd18c7.png)

2016-11-06 07:43 UTC, Dotokoto commented
:tomato: Пиши, как поправишь замечания

2016-11-06 14:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 14:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-06 14:21 UTC, AnastasiaBabushkina commented
🍏

2016-11-06 15:40 UTC, dotokoto commented on index.css
> +    src: local('CormorantInfant'), url(CormorantInfant-Bold.woff)
Лучше url вынести в отдельную строку к format (и каждый local и url писать с новой строки)

2016-11-06 15:42 UTC, dotokoto commented on index.css
> +.vertical_right
В этом селекторе и том, который выше, очень много одинаковых правил. Лучше одинаковые объединить 

```
vertical_right,
vertical_left
{
...
}
```

2016-11-06 15:43 UTC, dotokoto commented on index.css
> +    float: left;
А нужен ли float тут? Кажется, что без него точно так же выглядит

2016-11-06 15:45 UTC, Dotokoto commented
Ну кажется остались только маленькие замечания, думаю их быстро поправишь

2016-11-06 15:45 UTC, Dotokoto commented
:rocket:

2016-11-06 15:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 15:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-06 16:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-07 11:52 UTC, AnastasiaBabushkina commented
🍏

2016-11-08 08:54 UTC, mokhov commented
Очень плохо что картинки масштабируются не пропорционально

2016-11-08 08:59 UTC, mokhov requested changes
🍅

2016-11-08 08:59 UTC, mokhov commented on index.css
> +    word-wrap: break-word;
Новое название этого свойства https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

2016-11-08 08:59 UTC, mokhov commented on index.html
> +    <div class="under-header">
Я не понял почему ты это вынесла за пределы `header`, это бы и CSS облегчило

2016-11-08 08:59 UTC, mokhov commented on index.html
> +                <q>Кто лучше в качестве домашнего питомца – кошки или собаки?</q>
Зачем тут q?

2016-11-08 09:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 09:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-08 09:29 UTC, AnastasiaBabushkina commented
🍏

2016-11-10 16:15 UTC, closed without merging